import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  const today = new Date();

  const founderDeck = await prisma.deck.findFirst({ where: { name: "Founder Vocabulary" } });
  if (!founderDeck) throw new Error("Founder Vocabulary deck not found");

  const existing = await prisma.card.findMany({
    where: { deckId: founderDeck.id },
    select: { front: true },
  });
  const existingFronts = new Set(existing.map((c) => c.front.toLowerCase()));

  const words = [
    // ── COMPANY REGISTRATION ─────────────────────────────────────────────────
    {
      front: "Articles of Association",
      back: "The constitutional document of a UK/Nigerian company that sets out the internal rules governing how the company is run — director powers, shareholder rights, meeting procedures.",
      partOfSpeech: "noun",
      example: "Before onboarding investors, review the Articles of Association to confirm what approvals require a shareholder vote versus a board resolution.",
      hook: "If the shareholders agreement is the deal, the Articles are the rulebook the deal lives inside.",
      synonyms: "company constitution, Articles, AoA, bylaws (US equivalent)",
    },
    {
      front: "shareholders agreement",
      back: "A private contract between company shareholders defining their rights, obligations, and protections — covering things the Articles cannot, like tag-along rights, pre-emption rights, and founder vesting.",
      partOfSpeech: "noun",
      example: "The shareholders agreement prevented either co-founder from selling shares without offering the other the right of first refusal.",
      hook: "The Articles are public. The shareholders agreement is private. The sensitive protections live there.",
      synonyms: "SHA, investment agreement, founder agreement",
    },
    {
      front: "certificate of incorporation",
      back: "The official document issued by Companies House (UK) or the Corporate Affairs Commission (Nigeria) confirming that a company legally exists as a separate entity from its founders.",
      partOfSpeech: "noun",
      example: "The bank required the certificate of incorporation before opening the business account.",
      hook: "It is the company's birth certificate — the moment it becomes real in the eyes of the law.",
      synonyms: "incorporation certificate, company registration certificate, cert of inc",
    },
    {
      front: "authorised share capital",
      back: "The maximum number of shares a company is permitted to issue under its Articles — not all of which need to be issued immediately.",
      partOfSpeech: "noun",
      example: "We incorporated with 10,000,000 authorised shares at £0.001 par value, issuing only 1,000,000 at founding to leave room for the option pool and future investors.",
      hook: "Authorised capital is the ceiling. Issued capital is what you've actually handed out.",
      synonyms: "authorised capital, share capital, authorised shares",
    },
    {
      front: "ordinary shares vs. preference shares",
      back: "Ordinary shares carry standard voting and dividend rights with no special protections. Preference shares rank ahead of ordinary shares in dividends and liquidation, and often carry anti-dilution or investor protections.",
      partOfSpeech: "noun",
      example: "Founders typically hold ordinary shares. Investors who want downside protection negotiate preference shares with a liquidation preference.",
      hook: "Ordinary shares are democratic. Preference shares are prioritised.",
      synonyms: "common vs. preferred (US terms), equity classes",
    },
    {
      front: "vesting schedule",
      back: "The timeline over which a founder or employee earns their equity — typically 4 years with a 1-year cliff, meaning nothing vests until year one, then the remainder vests monthly.",
      partOfSpeech: "noun",
      example: "If a co-founder leaves in month 10, before the cliff, they walk away with zero equity — the vesting schedule protects the company.",
      hook: "Vesting is not about receiving shares. It is about earning the right to keep them over time.",
      synonyms: "equity vesting, share vesting, 4-year vest",
    },
    {
      front: "cliff",
      back: "The minimum period a founder or employee must stay before any equity vests — typically 12 months. If they leave before the cliff, they receive no shares.",
      partOfSpeech: "noun",
      example: "The cliff exists to ensure early hires and co-founders are genuinely committed before equity becomes theirs.",
      hook: "The cliff is the line before the ledge. Cross it or walk away with nothing.",
      synonyms: "vesting cliff, 1-year cliff, minimum vesting period",
    },
    {
      front: "registered office",
      back: "The official address of a company as registered with Companies House — where legal documents and government correspondence are sent. Does not have to be where the company actually operates.",
      partOfSpeech: "noun",
      example: "Many founders use a registered office service rather than their home address to keep their personal address off the public register.",
      hook: "The registered office is the address the law sends mail to — not necessarily where work happens.",
      synonyms: "registered address, company address, statutory address",
    },
    {
      front: "beneficial ownership",
      back: "The true owner of shares who enjoys the financial benefits — as distinct from the legal or registered owner. Regulators and banks increasingly require full beneficial ownership disclosure to prevent hidden control.",
      partOfSpeech: "noun",
      example: "Even if shares are held in trust, regulators require disclosure of the beneficial owner — the person who actually benefits from those shares.",
      hook: "Beneficial ownership answers: who actually wins when this company succeeds?",
      synonyms: "ultimate beneficial owner, UBO, true ownership",
    },
    {
      front: "confirmation statement",
      back: "An annual filing required by Companies House (UK) confirming that the public information about a company — directors, shareholders, registered office — is accurate and up to date.",
      partOfSpeech: "noun",
      example: "Even if nothing changes, you must file a confirmation statement every 12 months or the company risks being struck off.",
      hook: "It is not a financial report — it is the government asking: 'Is this still correct?'",
      synonyms: "annual return (old name), Companies House filing, statutory update",
    },

    // ── SAAS LAUNCH & METRICS ────────────────────────────────────────────────
    {
      front: "MRR",
      back: "Monthly Recurring Revenue — the predictable revenue a SaaS company earns each month from active subscriptions, excluding one-off payments.",
      partOfSpeech: "noun",
      example: "After the first 20 paying customers, MRR was £4,200 — enough to prove the pricing model before scaling acquisition.",
      hook: "MRR is the heartbeat of a SaaS business. Investors read it every month the way you check a pulse.",
      synonyms: "monthly recurring revenue, subscription revenue, contracted MRR",
    },
    {
      front: "ARR",
      back: "Annual Recurring Revenue — MRR multiplied by 12. Used to express the run-rate scale of a SaaS business and to benchmark against industry milestones like $1M ARR.",
      partOfSpeech: "noun",
      example: "Hitting $1M ARR is the standard signal that a SaaS business has found genuine repeatable demand.",
      hook: "ARR converts the monthly snapshot into the yearly story investors use to value the company.",
      synonyms: "annual recurring revenue, run rate, revenue run rate",
    },
    {
      front: "churn",
      back: "The rate at which customers cancel or stop paying — the single biggest threat to long-term SaaS growth. Logo churn counts customers lost; revenue churn counts money lost.",
      partOfSpeech: "noun",
      example: "A 5% monthly churn wipes out over half the customer base in a year — even fast acquisition cannot outrun it.",
      hook: "Churn is the hole in the bucket. It does not matter how fast you pour water in if water keeps draining out.",
      synonyms: "attrition, cancellation rate, customer loss",
    },
    {
      front: "net revenue retention",
      back: "NRR measures what percentage of last period's revenue you still have this period from the same customers — including expansions, contractions, and churn. Above 100% means you grow even with zero new customers.",
      partOfSpeech: "noun",
      example: "An NRR of 120% means existing customers are spending 20% more — the business grows even if acquisition stops entirely.",
      hook: "NRR above 100% is the SaaS superpower: the existing base funds growth before new sales are made.",
      synonyms: "net dollar retention, NDR, NRR",
    },
    {
      front: "CAC",
      back: "Customer Acquisition Cost — the total spend on sales and marketing divided by the number of new customers acquired in a given period.",
      partOfSpeech: "noun",
      example: "If you spend £10,000 on ads in a month and acquire 50 customers, your CAC is £200 per customer.",
      hook: "CAC is the price you pay to earn one customer. The question is whether that customer is worth it.",
      synonyms: "customer acquisition cost, cost per customer, acquisition cost",
    },
    {
      front: "LTV",
      back: "Lifetime Value — the total revenue a business can expect from a single customer over the entire length of their relationship.",
      partOfSpeech: "noun",
      example: "If a customer pays £50/month and stays for an average of 24 months, the LTV is £1,200.",
      hook: "LTV is what each customer is actually worth — not what they pay this month but what they are worth over time.",
      synonyms: "customer lifetime value, CLV, lifetime revenue per customer",
    },
    {
      front: "LTV:CAC ratio",
      back: "The ratio of a customer's lifetime value to the cost of acquiring them. A ratio of 3:1 or higher is the benchmark for a healthy SaaS business. Below 1:1 means you are losing money on every customer.",
      partOfSpeech: "noun",
      example: "At £1,200 LTV and £200 CAC, the LTV:CAC ratio is 6:1 — well above the 3:1 minimum investors look for.",
      hook: "3:1 is survival. 5:1 is healthy. Below 1:1 is a business that shrinks the more it sells.",
      synonyms: "unit economics, LTV to CAC, payback ratio",
    },
    {
      front: "payback period",
      back: "The number of months it takes to recover the cost of acquiring a customer from the gross margin they generate. Under 12 months is strong; over 24 months is a red flag.",
      partOfSpeech: "noun",
      example: "With £200 CAC and £50/month gross margin, the payback period is 4 months — fast enough to reinvest in the next customer quickly.",
      hook: "Payback period is how long your business is underwater per customer before it starts making money.",
      synonyms: "CAC payback, months to recover CAC, breakeven per customer",
    },
    {
      front: "burn rate",
      back: "The rate at which a company spends its cash reserves each month — net burn is after revenue, gross burn is total spend.",
      partOfSpeech: "noun",
      example: "At £30,000 monthly burn and £180,000 in the bank, the runway is exactly 6 months.",
      hook: "Burn rate is the clock. Runway is how much time is left on it.",
      synonyms: "monthly burn, net burn, cash consumption rate",
    },
    {
      front: "runway",
      back: "The number of months a company can continue operating before running out of cash, given current burn rate and revenue. 18+ months is considered safe; under 6 months is an emergency.",
      partOfSpeech: "noun",
      example: "Closing the round gave us 24 months of runway — enough time to reach MRR milestones without distraction.",
      hook: "Runway is not a metric. It is a deadline. Everything you do is relative to how much of it remains.",
      synonyms: "cash runway, months of cash, operating runway",
    },
    {
      front: "gross margin",
      back: "Revenue minus the direct cost of delivering the product, expressed as a percentage. SaaS businesses typically target 70–90% gross margins because infrastructure costs are low relative to revenue.",
      partOfSpeech: "noun",
      example: "A SaaS product with 80% gross margin means 80p of every £1 is available for growth, salaries, and profit.",
      hook: "Gross margin is not about efficiency. It is about how much of every pound you get to keep before investing in growth.",
      synonyms: "gross profit margin, contribution margin, product margin",
    },
    {
      front: "rule of 40",
      back: "A benchmark for SaaS health: revenue growth rate % plus profit margin % should equal or exceed 40. A company growing at 50% with -10% margins scores 40. A company growing at 20% needs 20%+ margins.",
      partOfSpeech: "noun",
      example: "Investors use the Rule of 40 to evaluate whether a SaaS company is growing fast enough to justify losses, or profitable enough to justify slower growth.",
      hook: "The Rule of 40 gives fast, unprofitable businesses a way to prove they are still healthy — and slow, profitable ones the same.",
      synonyms: "SaaS health benchmark, growth + margin metric",
    },
    {
      front: "deferred revenue",
      back: "Money received from customers for services not yet delivered — recognised as a liability on the balance sheet until the service period passes. Common in annual SaaS contracts paid upfront.",
      partOfSpeech: "noun",
      example: "A customer who pays £1,200 upfront for an annual plan creates £1,200 in deferred revenue, recognised at £100/month.",
      hook: "Deferred revenue is cash you have but have not earned yet. It is the revenue your next 12 months are already pre-loaded with.",
      synonyms: "unearned revenue, contract liability, prepaid revenue",
    },

    // ── FUNDRAISING & INVESTOR ROOMS ─────────────────────────────────────────
    {
      front: "SAFE",
      back: "Simple Agreement for Future Equity — an investment instrument that converts into equity at a future priced round, without setting a current valuation. Simpler and cheaper than a convertible note.",
      partOfSpeech: "noun",
      example: "We raised our pre-seed on SAFEs — investors got in quickly without the legal cost of a full priced round, and we avoided setting a valuation too early.",
      hook: "A SAFE says: give me money now, I will give you shares later when the price is clearer.",
      synonyms: "simple agreement for future equity, YC SAFE, pre-seed instrument",
    },
    {
      front: "convertible note",
      back: "A short-term debt instrument that converts into equity at a future funding round, typically at a discount or with a valuation cap. Unlike a SAFE, it accrues interest and has a maturity date.",
      partOfSpeech: "noun",
      example: "The angel used a convertible note with a £3M cap — meaning they convert at whichever is lower: the cap or the next round price.",
      hook: "A convertible note is debt that wants to become equity. It has a time limit and a cost.",
      synonyms: "convertible debt, bridge note, convertible loan",
    },
    {
      front: "pre-money vs. post-money valuation",
      back: "Pre-money valuation is what the company is worth before new investment. Post-money is pre-money plus the new investment. Investors own the investment divided by post-money.",
      partOfSpeech: "noun",
      example: "At a £5M pre-money valuation with a £1M investment, post-money is £6M — the investor owns 1/6 or ~16.7%.",
      hook: "Pre-money is the price tag before the cash. Post-money is the total after. Ownership is calculated on post.",
      synonyms: "pre-money, post-money, company valuation",
    },
    {
      front: "dilution",
      back: "The reduction in an existing shareholder's ownership percentage when new shares are issued — typically when raising a new round or expanding the option pool.",
      partOfSpeech: "noun",
      example: "Raising a £2M round at a £8M pre-money valuation diluted existing shareholders by 20%.",
      hook: "Dilution is not losing shares. It is losing percentage. The slice gets smaller when the pie gets bigger.",
      synonyms: "equity dilution, percentage reduction, ownership dilution",
    },
    {
      front: "cap table",
      back: "Capitalisation table — a document showing every person or entity that owns equity in a company, how much they own, and what type of shares they hold.",
      partOfSpeech: "noun",
      example: "Before signing the term sheet, the investor asked to see a fully diluted cap table showing the founders, advisors, and option pool.",
      hook: "The cap table is the ledger of who owns what. It tells the real story of control and value.",
      synonyms: "capitalisation table, share register, ownership table",
    },
    {
      front: "option pool",
      back: "A block of shares reserved for future employees, advisors, and contractors — typically 10–20% of the fully diluted company, created before or as part of a funding round.",
      partOfSpeech: "noun",
      example: "Investors often require a 15% option pool before calculating their ownership — the option pool shuffle dilutes founders, not investors.",
      hook: "The option pool is the company's talent budget expressed in equity.",
      synonyms: "employee stock option pool, ESOP pool, equity pool",
    },
    {
      front: "option pool shuffle",
      back: "The practice where investors require the option pool to be created and included in the pre-money valuation — which dilutes the founders rather than the new investors.",
      partOfSpeech: "noun",
      example: "The term sheet looked like a £5M pre-money deal, but with a 20% option pool shuffle, founders were effectively being valued lower before the investment went in.",
      hook: "The option pool shuffle is a hidden dilution mechanism dressed as standard terms.",
      synonyms: "pre-money option pool, option pool inclusion, founder dilution trick",
    },
    {
      front: "liquidation preference",
      back: "The right of preferred shareholders to receive their money back before ordinary shareholders in a liquidation or acquisition — typically 1x, meaning investors get their money back first.",
      partOfSpeech: "noun",
      example: "With a 1x non-participating liquidation preference, investors get their money back first in an acquisition — anything above that is shared with common shareholders.",
      hook: "Liquidation preference is not about bankruptcy. It determines who gets paid first when the company is sold.",
      synonyms: "liquidation priority, preferred return, downside protection",
    },
    {
      front: "pro rata rights",
      back: "The right of an existing investor to participate in future funding rounds to maintain their percentage ownership — preventing dilution as the company grows.",
      partOfSpeech: "noun",
      example: "The angel investor negotiated pro rata rights so they could follow their investment in the Series A and keep their 5% stake.",
      hook: "Pro rata rights are the investor's right to keep their seat at the table as the round gets bigger.",
      synonyms: "follow-on rights, preemption rights, participation rights",
    },
    {
      front: "term sheet",
      back: "A non-binding document outlining the key terms of an investment deal — valuation, ownership, board composition, liquidation preference — before full legal documentation is drafted.",
      partOfSpeech: "noun",
      example: "The term sheet arrived three weeks after the first meeting. Accepting it is not the deal — it is the agreement to do the deal on these terms.",
      hook: "A term sheet is a handshake in writing. It is not legally binding, but the terms almost always survive into the final documents.",
      synonyms: "investment term sheet, deal terms, letter of intent (for investment)",
    },
    {
      front: "lead investor",
      back: "The investor who sets the terms, does the primary due diligence, and takes the largest portion of a round — other investors follow their lead.",
      partOfSpeech: "noun",
      example: "Finding a lead investor is the hardest part of raising a round — once they commit, other investors follow without needing to re-evaluate the deal.",
      hook: "The lead investor is the anchor. Once they are in, the round fills.",
      synonyms: "lead VC, anchor investor, lead partner",
    },
    {
      front: "drag-along rights",
      back: "A provision that allows majority shareholders to force minority shareholders to agree to a sale of the company on the same terms.",
      partOfSpeech: "noun",
      example: "Drag-along rights prevented a minority shareholder from blocking an acquisition that the majority and investors all supported.",
      hook: "Drag-along prevents one dissenting shareholder from holding an exit hostage.",
      synonyms: "drag-along, compulsory sale provision, forced sale clause",
    },
    {
      front: "right of first refusal",
      back: "The right to purchase shares before the owner can sell them to a third party — meaning existing shareholders or the company get first chance to buy.",
      partOfSpeech: "noun",
      example: "The shareholders agreement included a right of first refusal — if a founder wanted to sell shares, other shareholders could match any offer before an outsider could buy.",
      hook: "ROFR is the existing owner's right to be first in line before a stranger gets the opportunity.",
      synonyms: "ROFR, first refusal right, preemption right",
    },

    // ── WORDS YOU DON'T KNOW YOU NEED ────────────────────────────────────────
    {
      front: "fiduciary duty",
      back: "A legal obligation to act in the best interest of another party — as a company director, you owe fiduciary duties to shareholders, requiring you to prioritise their interests over your own.",
      partOfSpeech: "noun",
      example: "A director who steers a contract to their own side business may breach fiduciary duty even if the deal seems fair — the obligation is to the company, not to themselves.",
      hook: "Fiduciary duty means the company's interest comes before yours — always, legally.",
      synonyms: "director's duty, duty of loyalty, legal obligation to act in good faith",
    },
    {
      front: "assignment of inventions",
      back: "A clause (in employment or contractor agreements) that transfers intellectual property created during the relationship to the company — not to the individual who created it.",
      partOfSpeech: "noun",
      example: "Every engineer who works on the product — employee or contractor — must sign an assignment of inventions clause, or the IP ownership of their code is legally ambiguous.",
      hook: "Without it, the developer owns the code they wrote. With it, the company does.",
      synonyms: "IP assignment, invention assignment, intellectual property transfer clause",
    },
    {
      front: "work-for-hire doctrine",
      back: "The legal principle that work created by an employee within the scope of their employment belongs to the employer, not the creator — but this does not automatically apply to contractors, who need a written agreement.",
      partOfSpeech: "noun",
      example: "The work-for-hire doctrine protects employed engineers' output, but a freelance developer retains rights to their work unless a contract explicitly assigns it to the company.",
      hook: "Employees: the company owns it by default. Contractors: you need a contract that says so.",
      synonyms: "work made for hire, employer IP ownership, contractor IP risk",
    },
    {
      front: "piercing the corporate veil",
      back: "A legal action where courts hold company directors or shareholders personally liable for company debts or wrongdoing — typically when the corporate structure was abused or the company was a sham.",
      partOfSpeech: "noun",
      example: "Founders who mix personal and company finances, or use the company purely to avoid personal debts, risk piercing the corporate veil — losing the limited liability protection that incorporation provides.",
      hook: "The corporate veil protects you from the company's debts. If you treat the company as your piggy bank, the veil disappears.",
      synonyms: "personal liability exposure, veil lifting, loss of limited liability",
    },
    {
      front: "due diligence",
      back: "The investigation and verification process conducted by investors, acquirers, or partners before committing to a deal — covering financials, legal documents, IP, contracts, and team.",
      partOfSpeech: "noun",
      example: "The investor loved the pitch but said due diligence would take 4–6 weeks — they needed to verify the financials, review contracts, and confirm IP ownership before wiring money.",
      hook: "Due diligence is the investor's version of reading the small print — in great detail, with lawyers.",
      synonyms: "DD, legal and financial review, investor diligence",
    },
    {
      front: "representations and warranties",
      back: "Legally binding statements made by one party in a contract asserting that certain facts are true — if they turn out to be false, the other party can claim damages.",
      partOfSpeech: "noun",
      example: "Founders sign reps and warranties confirming no pending litigation, clean IP ownership, and accurate financials — any misrepresentation can unwind the deal.",
      hook: "Representations and warranties are promises with legal teeth. If they are wrong, they cost money.",
      synonyms: "reps and warranties, contractual statements, deal warranties",
    },
    {
      front: "indemnification",
      back: "A contractual obligation by one party to compensate the other for losses or liabilities arising from specified events — often used to protect investors from founder misconduct or misrepresentation.",
      partOfSpeech: "noun",
      example: "The indemnification clause required the founders to personally compensate investors if undisclosed litigation materialised after closing.",
      hook: "Indemnification is the contractual answer to: who pays if something goes wrong that was someone's fault?",
      synonyms: "indemnity, hold harmless clause, contractual protection",
    },
    {
      front: "data processing agreement",
      back: "A legally required contract between a company and any third party that processes personal data on its behalf — mandated under GDPR and UK data protection law.",
      partOfSpeech: "noun",
      example: "Before integrating an AI provider that processes user data, the company must execute a data processing agreement under UK GDPR or risk regulatory breach.",
      hook: "If your SaaS handles personal data and uses external processors, a DPA is not optional — it is a legal requirement.",
      synonyms: "DPA, data processing contract, GDPR agreement",
    },
    {
      front: "SOC 2",
      back: "A security compliance framework that demonstrates a company has controls in place to protect customer data — increasingly required by enterprise customers before signing SaaS contracts.",
      partOfSpeech: "noun",
      example: "The enterprise prospect would not sign a contract without a SOC 2 Type II report — achieving compliance was the gating requirement for the entire upmarket segment.",
      hook: "SOC 2 is not a product feature. It is the proof enterprise buyers need before they trust you with their data.",
      synonyms: "SOC 2 compliance, security audit report, system and organisation controls",
    },
    {
      front: "service level agreement",
      back: "A contractual commitment to specific standards of service — typically uptime percentage, response time, and remedies if those standards are not met.",
      partOfSpeech: "noun",
      example: "The enterprise contract included a 99.9% uptime SLA with service credits issued automatically if availability dropped below that threshold.",
      hook: "An SLA is the promise on paper. It turns reliability into a contractual obligation with consequences.",
      synonyms: "SLA, uptime guarantee, service commitment",
    },
    {
      front: "MFN clause",
      back: "Most Favoured Nation — a contractual provision ensuring that if you later offer better terms to another party, those better terms automatically apply to the current party too.",
      partOfSpeech: "noun",
      example: "Early SAFE investors with an MFN clause will automatically receive the same discount or lower cap offered to later investors in the same stage.",
      hook: "MFN means: whatever better deal you do next, I get it too.",
      synonyms: "most favoured nation, MFN, best terms guarantee",
    },
    {
      front: "signalling risk",
      back: "The reputational damage caused when a current investor declines to invest in a company's next round — which signals to new investors that the insider with the most information chose not to follow on.",
      partOfSpeech: "noun",
      example: "Taking money from large VCs at pre-seed creates signalling risk — if they pass on the seed round, every other investor asks why.",
      hook: "Signalling risk is when your best-informed supporter says no in public without saying a word.",
      synonyms: "investor signal, follow-on signal, insider signal",
    },
    {
      front: "MOIC",
      back: "Multiple on Invested Capital — a measure of investment return calculated as total value returned divided by total capital invested. A 3x MOIC means the investor tripled their money.",
      partOfSpeech: "noun",
      example: "At a £40M acquisition after a £500K SAFE, the investor's MOIC was 80x — an exceptional outcome that benchmarks against other deals in the fund.",
      hook: "MOIC is the simplest answer to: how much money did this investment make?",
      synonyms: "investment multiple, return multiple, money-on-money return",
    },
    {
      front: "IRR",
      back: "Internal Rate of Return — the annualised rate of return on an investment, accounting for how long the money was invested. A 3x MOIC over 2 years is a much higher IRR than the same return over 10 years.",
      partOfSpeech: "noun",
      example: "A quick exit with modest returns can deliver a strong IRR — time is the denominator investors rarely talk about but always care about.",
      hook: "MOIC tells you how much. IRR tells you how fast. VCs care about both.",
      synonyms: "internal rate of return, annualised return, time-weighted return",
    },
    {
      front: "down round",
      back: "A funding round where the company's valuation is lower than in the previous round — typically seen as a sign of difficulty and dilutive to earlier investors and founders.",
      partOfSpeech: "noun",
      example: "After missing growth targets, the company raised a down round — painful for founders who lost significant ownership, and triggering anti-dilution provisions for earlier investors.",
      hook: "A down round is not just a lower price. It is a public signal that the last valuation was wrong.",
      synonyms: "down-round financing, valuation reduction, dilutive round",
    },
    {
      front: "anti-dilution provision",
      back: "A protection for investors that adjusts their share count if the company raises money at a lower valuation — so the investor's effective price per share is reduced to compensate for the down round.",
      partOfSpeech: "noun",
      example: "Investors with anti-dilution provisions in a down round received additional shares to protect their percentage — founders absorbed the full dilution.",
      hook: "Anti-dilution is insurance for investors against a valuation that turns out to have been too high.",
      synonyms: "anti-dilution protection, price ratchet, dilution adjustment",
    },
    {
      front: "liquidation waterfall",
      back: "The order in which proceeds from a sale or liquidation are distributed to shareholders — typically: debt, preferred shareholders (with liquidation preferences), then common shareholders.",
      partOfSpeech: "noun",
      example: "In the acquisition, the liquidation waterfall meant investors received their 1x preference first, leaving £2M for founders on a £5M deal.",
      hook: "The waterfall determines who gets paid, in what order. Being last in the waterfall can mean getting nothing.",
      synonyms: "distribution waterfall, liquidation preference stack, exit proceeds order",
    },
    {
      front: "earnout",
      back: "A portion of an acquisition price that is paid only if the company hits certain performance targets after closing — used to bridge valuation gaps between buyer and seller.",
      partOfSpeech: "noun",
      example: "The acquisition was £8M upfront plus a £2M earnout tied to hitting £500K ARR in the 12 months post-close.",
      hook: "An earnout is deferred trust. The buyer believes in you enough to pay for it — but only after you prove it.",
      synonyms: "contingent consideration, performance payout, deferred acquisition payment",
    },
    {
      front: "product-market fit",
      back: "The point at which a product genuinely satisfies a strong market demand — users come back, retention is high, and growth happens with minimal push. Marc Andreessen's framework: you know it when you feel it.",
      partOfSpeech: "noun",
      example: "PMF is not about investor enthusiasm or press coverage. It is when the market pulls the product, rather than the founder pushing it.",
      hook: "Before PMF, everything is expensive. After PMF, everything is faster.",
      synonyms: "PMF, product-market alignment, market pull",
    },
    {
      front: "north star metric",
      back: "The single metric that best captures the core value the product delivers to users — the one number the whole team optimises around as a proxy for long-term success.",
      partOfSpeech: "noun",
      example: "Soro Soke's north star metric could be 'cards reviewed this week' — a user who reviews regularly retains vocabulary. Everything else follows from that.",
      hook: "The north star metric is the one number that is true before and after you hit it.",
      synonyms: "NSM, primary metric, focus metric, key metric",
    },
    {
      front: "cohort analysis",
      back: "Tracking a specific group of users who started at the same time to measure how their behaviour changes over time — the most accurate way to understand retention and lifetime value.",
      partOfSpeech: "noun",
      example: "A cohort analysis of January sign-ups showed 60% still active in month three — much stronger than the blended average, which was diluted by recent signups who had not had time to churn.",
      hook: "Cohort analysis separates the question 'how many users do we have' from 'how many are still here from last month'.",
      synonyms: "cohort retention, user cohort tracking, longitudinal user analysis",
    },
    {
      front: "logo churn vs. revenue churn",
      back: "Logo churn counts customers lost; revenue churn counts money lost. Losing a small customer can be 1 logo but low revenue churn. Losing one enterprise customer can be 1 logo but devastating revenue churn.",
      partOfSpeech: "noun",
      example: "Losing 5 startups from a 100-customer base is 5% logo churn but only 1% revenue churn if enterprise customers dominate revenue.",
      hook: "Logo churn counts heads. Revenue churn counts pounds. They can tell very different stories.",
      synonyms: "customer churn vs. MRR churn, gross revenue retention vs. logo retention",
    },
    {
      front: "negative churn",
      back: "When expansion revenue from existing customers exceeds revenue lost from churn — meaning the base grows even without acquiring a single new customer.",
      partOfSpeech: "noun",
      example: "Because accounts upgraded faster than they cancelled, the company achieved negative churn — a self-sustaining growth engine built entirely from existing customers.",
      hook: "Negative churn is the SaaS endgame: existing customers grow the revenue even as some leave.",
      synonyms: "net negative churn, expansion > churn, NRR above 100%",
    },
    {
      front: "ICP qualification",
      back: "The process of evaluating whether a potential customer actually matches your ideal customer profile before investing significant sales resources — filtering leads by the attributes that predict success.",
      partOfSpeech: "noun",
      example: "After ICP qualification, the sales team stopped pursuing SMEs and focused entirely on mid-market SaaS companies — conversion rates doubled because every meeting was with the right type of buyer.",
      hook: "ICP qualification is not about rejecting customers. It is about spending energy where the probability of a great outcome is highest.",
      synonyms: "lead qualification, ICP fit, customer screening",
    },
  ];

  let added = 0;
  for (const word of words) {
    if (existingFronts.has(word.front.toLowerCase())) {
      console.log(`  skip: ${word.front} (already exists)`);
      continue;
    }
    await prisma.card.create({
      data: {
        deckId: founderDeck.id,
        front: word.front,
        back: word.back,
        partOfSpeech: word.partOfSpeech,
        example: word.example,
        hook: word.hook,
        synonyms: word.synonyms,
        kind: "FOUNDER",
        dueAt: today,
      },
    });
    console.log(`  added: ${word.front}`);
    added++;
  }

  console.log(`\nFounder Vocabulary: ${added} new cards added`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
