import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

type C = {
  name: string; flag: string; capital: string; continent: string;
  population?: string; currency?: string; languages: string;
  nationalFood?: string; phraseLanguage?: string;
  phraseHi?: string; phraseMorning?: string; phraseAfternoon?: string;
  funFact?: string;
};

const AFRICA: C[] = [
  { name: "Algeria", flag: "🇩🇿", capital: "Algiers", continent: "Africa", population: "~45M", currency: "Algerian Dinar", languages: "Arabic, Berber", nationalFood: "Couscous with vegetables and lamb", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)", funFact: "Largest country in Africa by area" },
  { name: "Angola", flag: "🇦🇴", capital: "Luanda", continent: "Africa", population: "~35M", currency: "Kwanza", languages: "Portuguese", nationalFood: "Muamba de Galinha (palm oil chicken stew)", phraseLanguage: "Portuguese", phraseHi: "Olá", phraseMorning: "Bom dia", phraseAfternoon: "Boa tarde" },
  { name: "Benin", flag: "🇧🇯", capital: "Porto-Novo", continent: "Africa", population: "~13M", currency: "West African CFA Franc", languages: "French", nationalFood: "Aloko (fried plantains with sauce)", phraseLanguage: "French", phraseHi: "Bonjour / Salut", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi" },
  { name: "Botswana", flag: "🇧🇼", capital: "Gaborone", continent: "Africa", population: "~2.6M", currency: "Pula", languages: "English, Setswana", nationalFood: "Seswaa (slow-cooked pounded meat)", phraseLanguage: "Setswana", phraseHi: "Dumela", phraseMorning: "Dumela — o tsogile jang?", phraseAfternoon: "Dumela", funFact: "One of Africa's most stable democracies" },
  { name: "Burkina Faso", flag: "🇧🇫", capital: "Ouagadougou", continent: "Africa", population: "~22M", currency: "West African CFA Franc", languages: "French, Mooré, Dioula", nationalFood: "Riz gras (spiced rice with meat and vegetables)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi" },
  { name: "Burundi", flag: "🇧🇮", capital: "Gitega", continent: "Africa", population: "~12M", currency: "Burundian Franc", languages: "Kirundi, French, English", nationalFood: "Boko (beans and plantains stew)", phraseLanguage: "Kirundi", phraseHi: "Bite (BEE-teh)", phraseMorning: "Mwaramutse", phraseAfternoon: "Mwiriwe" },
  { name: "Cabo Verde", flag: "🇨🇻", capital: "Praia", continent: "Africa", population: "~0.6M", currency: "Cape Verdean Escudo", languages: "Portuguese, Kriolu", nationalFood: "Cachupa (slow-cooked stew of corn and beans)", phraseLanguage: "Portuguese", phraseHi: "Olá", phraseMorning: "Bom dia", phraseAfternoon: "Boa tarde" },
  { name: "Cameroon", flag: "🇨🇲", capital: "Yaoundé", continent: "Africa", population: "~27M", currency: "Central African CFA Franc", languages: "French, English", nationalFood: "Ndolé (stew with groundnuts and bitter leaves)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi", funFact: "Called 'Africa in miniature' for its diverse landscapes" },
  { name: "Central African Republic", flag: "🇨🇫", capital: "Bangui", continent: "Africa", population: "~5M", currency: "Central African CFA Franc", languages: "French, Sango", nationalFood: "Gozo (cassava paste with sauce)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi" },
  { name: "Chad", flag: "🇹🇩", capital: "N'Djamena", continent: "Africa", population: "~17M", currency: "Central African CFA Franc", languages: "French, Arabic", nationalFood: "Daraba (okra and peanut butter stew)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)" },
  { name: "Comoros", flag: "🇰🇲", capital: "Moroni", continent: "Africa", population: "~0.9M", currency: "Comorian Franc", languages: "Comorian, Arabic, French", nationalFood: "Langouste à la vanille (vanilla lobster)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi" },
  { name: "Republic of Congo", flag: "🇨🇬", capital: "Brazzaville", continent: "Africa", population: "~6M", currency: "Central African CFA Franc", languages: "French, Lingala, Kituba", nationalFood: "Saka Saka (cassava leaf stew)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi" },
  { name: "DR Congo", flag: "🇨🇩", capital: "Kinshasa", continent: "Africa", population: "~100M", currency: "Congolese Franc", languages: "French, Lingala, Kikongo, Swahili", nationalFood: "Moambe (palm nut chicken stew)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi", funFact: "Second largest country in Africa by area" },
  { name: "Djibouti", flag: "🇩🇯", capital: "Djibouti City", continent: "Africa", population: "~1M", currency: "Djiboutian Franc", languages: "French, Arabic", nationalFood: "Skudahkharis (spiced rice with goat)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)" },
  { name: "Egypt", flag: "🇪🇬", capital: "Cairo", continent: "Africa", population: "~105M", currency: "Egyptian Pound", languages: "Arabic", nationalFood: "Koshari (rice, lentils, pasta with tomato sauce)", phraseLanguage: "Arabic", phraseHi: "أهلاً (Ahlan)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)", funFact: "Home to the ancient pyramids, one of the Seven Wonders of the World" },
  { name: "Equatorial Guinea", flag: "🇬🇶", capital: "Malabo", continent: "Africa", population: "~1.5M", currency: "Central African CFA Franc", languages: "Spanish, French, Portuguese", nationalFood: "Pepesoup (spiced fish broth)", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes" },
  { name: "Eritrea", flag: "🇪🇷", capital: "Asmara", continent: "Africa", population: "~3.5M", currency: "Eritrean Nakfa", languages: "Tigrinya, Arabic, English", nationalFood: "Injera with zigni (sourdough flatbread with spiced meat stew)", phraseLanguage: "Tigrinya", phraseHi: "ሰላም (Selam)", phraseMorning: "ደሓን ሓዲርካ (Dehan hadirka)", phraseAfternoon: "ደሓን ዋዒልካ (Dehan waelka)" },
  { name: "Eswatini", flag: "🇸🇿", capital: "Mbabane", continent: "Africa", population: "~1.2M", currency: "Lilangeni", languages: "siSwati, English", nationalFood: "Sishwala (thick maize porridge with meat)", phraseLanguage: "siSwati", phraseHi: "Sawubona", phraseMorning: "Livukile", phraseAfternoon: "Letfokotfu" },
  { name: "Ethiopia", flag: "🇪🇹", capital: "Addis Ababa", continent: "Africa", population: "~125M", currency: "Ethiopian Birr", languages: "Amharic, Oromo, Tigrinya", nationalFood: "Injera with various stews (kitfo, tibs, doro wat)", phraseLanguage: "Amharic", phraseHi: "ሰላም (Selam)", phraseMorning: "እንደምን አደሩ (Indemen aderu)", phraseAfternoon: "እንደምን ዋሉ (Indemen walu)", funFact: "One of only two African countries never colonised" },
  { name: "Gabon", flag: "🇬🇦", capital: "Libreville", continent: "Africa", population: "~2.3M", currency: "Central African CFA Franc", languages: "French", nationalFood: "Poulet Nyembwe (chicken in palm nut sauce)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi" },
  { name: "Gambia", flag: "🇬🇲", capital: "Banjul", continent: "Africa", population: "~2.7M", currency: "Dalasi", languages: "English, Mandinka, Wolof", nationalFood: "Benachin (jollof rice with fish or meat)", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Ghana", flag: "🇬🇭", capital: "Accra", continent: "Africa", population: "~33M", currency: "Ghanaian Cedi", languages: "English, Akan, Ewe", nationalFood: "Fufu with light soup or groundnut soup", phraseLanguage: "Twi (Akan)", phraseHi: "Agoo", phraseMorning: "Mema wo akye (Good morning)", phraseAfternoon: "Mema wo aha (Good afternoon)" },
  { name: "Guinea", flag: "🇬🇳", capital: "Conakry", continent: "Africa", population: "~13M", currency: "Guinean Franc", languages: "French, Pular, Mandinka", nationalFood: "Fouti (rice with various sauces)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi" },
  { name: "Guinea-Bissau", flag: "🇬🇼", capital: "Bissau", continent: "Africa", population: "~2M", currency: "West African CFA Franc", languages: "Portuguese, Kriolu", nationalFood: "Caldo de mancarra (groundnut soup with fish)", phraseLanguage: "Portuguese", phraseHi: "Olá", phraseMorning: "Bom dia", phraseAfternoon: "Boa tarde" },
  { name: "Ivory Coast", flag: "🇨🇮", capital: "Yamoussoukro", continent: "Africa", population: "~27M", currency: "West African CFA Franc", languages: "French, Dioula", nationalFood: "Attiéké (fermented cassava couscous with grilled fish)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi" },
  { name: "Kenya", flag: "🇰🇪", capital: "Nairobi", continent: "Africa", population: "~55M", currency: "Kenyan Shilling", languages: "Swahili, English", nationalFood: "Nyama choma (grilled meat) with ugali", phraseLanguage: "Swahili", phraseHi: "Habari", phraseMorning: "Habari za asubuhi", phraseAfternoon: "Habari za mchana", funFact: "Home to the Great Rift Valley and the Maasai Mara" },
  { name: "Lesotho", flag: "🇱🇸", capital: "Maseru", continent: "Africa", population: "~2.2M", currency: "Lesotho Loti", languages: "Sesotho, English", nationalFood: "Papa (stiff maize porridge) with moroho (cooked greens)", phraseLanguage: "Sesotho", phraseHi: "Lumela", phraseMorning: "Lumela — u phela joang?", phraseAfternoon: "Lumela", funFact: "Entirely surrounded by South Africa — a country within a country" },
  { name: "Liberia", flag: "🇱🇷", capital: "Monrovia", continent: "Africa", population: "~5M", currency: "Liberian Dollar", languages: "English", nationalFood: "Jollof rice / Cassava leaf soup", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Libya", flag: "🇱🇾", capital: "Tripoli", continent: "Africa", population: "~7M", currency: "Libyan Dinar", languages: "Arabic", nationalFood: "Bazeen (hard barley dough with spiced meat sauce)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)" },
  { name: "Madagascar", flag: "🇲🇬", capital: "Antananarivo", continent: "Africa", population: "~28M", currency: "Malagasy Ariary", languages: "Malagasy, French", nationalFood: "Romazava (meat and leafy green vegetable stew)", phraseLanguage: "Malagasy", phraseHi: "Salama", phraseMorning: "Manao ahoana ny maraina?", phraseAfternoon: "Manao ahoana ny tolakandro?", funFact: "Island nation with 90% of wildlife found nowhere else on Earth" },
  { name: "Malawi", flag: "🇲🇼", capital: "Lilongwe", continent: "Africa", population: "~20M", currency: "Malawian Kwacha", languages: "Chichewa, English", nationalFood: "Nsima (thick maize porridge) with chambo fish", phraseLanguage: "Chichewa", phraseHi: "Moni", phraseMorning: "Mwadzuka bwanji", phraseAfternoon: "Mwachita bwanji" },
  { name: "Mali", flag: "🇲🇱", capital: "Bamako", continent: "Africa", population: "~22M", currency: "West African CFA Franc", languages: "French, Bambara", nationalFood: "Tô (millet porridge with peanut or baobab sauce)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi" },
  { name: "Mauritania", flag: "🇲🇷", capital: "Nouakchott", continent: "Africa", population: "~4.6M", currency: "Mauritanian Ouguiya", languages: "Arabic, French", nationalFood: "Thieboudienne (fish and rice in tomato sauce)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)" },
  { name: "Mauritius", flag: "🇲🇺", capital: "Port Louis", continent: "Africa", population: "~1.3M", currency: "Mauritian Rupee", languages: "English, French, Mauritian Creole", nationalFood: "Dholl puri (flatbread with curried lentils)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi" },
  { name: "Morocco", flag: "🇲🇦", capital: "Rabat", continent: "Africa", population: "~37M", currency: "Moroccan Dirham", languages: "Arabic, Berber (Tamazight), French", nationalFood: "Tagine / Couscous with seven vegetables", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)", funFact: "Fez is home to the world's oldest continuously operating university (859 AD)" },
  { name: "Mozambique", flag: "🇲🇿", capital: "Maputo", continent: "Africa", population: "~32M", currency: "Mozambican Metical", languages: "Portuguese", nationalFood: "Piri piri chicken (spicy grilled chicken with chilli)", phraseLanguage: "Portuguese", phraseHi: "Olá", phraseMorning: "Bom dia", phraseAfternoon: "Boa tarde" },
  { name: "Namibia", flag: "🇳🇦", capital: "Windhoek", continent: "Africa", population: "~2.6M", currency: "Namibian Dollar", languages: "English, Oshiwambo, Afrikaans", nationalFood: "Potjiekos (slow-cooked stew in cast iron pot)", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Niger", flag: "🇳🇪", capital: "Niamey", continent: "Africa", population: "~25M", currency: "West African CFA Franc", languages: "French, Hausa, Zarma", nationalFood: "Dambou (couscous with vegetables and peanut sauce)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi" },
  { name: "Nigeria", flag: "🇳🇬", capital: "Abuja", continent: "Africa", population: "~220M", currency: "Nigerian Naira", languages: "English, Hausa, Yoruba, Igbo", nationalFood: "Jollof rice / Egusi soup / Suya (spiced grilled meat)", phraseLanguage: "Yoruba", phraseHi: "E kaabo", phraseMorning: "E kaaro", phraseAfternoon: "E kaasan", funFact: "Most populous country in Africa" },
  { name: "Rwanda", flag: "🇷🇼", capital: "Kigali", continent: "Africa", population: "~13M", currency: "Rwandan Franc", languages: "Kinyarwanda, French, English", nationalFood: "Isombe (cassava leaves with eggplant and peanuts)", phraseLanguage: "Kinyarwanda", phraseHi: "Muraho", phraseMorning: "Mwaramutse", phraseAfternoon: "Mwiriwe" },
  { name: "São Tomé and Príncipe", flag: "🇸🇹", capital: "São Tomé", continent: "Africa", population: "~0.2M", currency: "São Tomé Dobra", languages: "Portuguese", nationalFood: "Calulu (sun-dried fish and vegetable stew)", phraseLanguage: "Portuguese", phraseHi: "Olá", phraseMorning: "Bom dia", phraseAfternoon: "Boa tarde" },
  { name: "Senegal", flag: "🇸🇳", capital: "Dakar", continent: "Africa", population: "~17M", currency: "West African CFA Franc", languages: "French, Wolof", nationalFood: "Thieboudienne (fish and rice — national dish)", phraseLanguage: "Wolof", phraseHi: "Salaam aleikum", phraseMorning: "Jàmm nga fanaan", phraseAfternoon: "Jàmm nga toog" },
  { name: "Seychelles", flag: "🇸🇨", capital: "Victoria", continent: "Africa", population: "~0.1M", currency: "Seychellois Rupee", languages: "Seychellois Creole, English, French", nationalFood: "Ladob (banana and sweet potato in coconut milk)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi" },
  { name: "Sierra Leone", flag: "🇸🇱", capital: "Freetown", continent: "Africa", population: "~8M", currency: "Sierra Leonean Leone", languages: "English, Krio", nationalFood: "Groundnut stew (peanut butter soup with chicken)", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Somalia", flag: "🇸🇴", capital: "Mogadishu", continent: "Africa", population: "~17M", currency: "Somali Shilling", languages: "Somali, Arabic", nationalFood: "Canjeero (sourdough flatbread) with hilib (spiced meat)", phraseLanguage: "Somali", phraseHi: "Nabadgelyo", phraseMorning: "Subax wanaagsan", phraseAfternoon: "Galab wanaagsan" },
  { name: "South Africa", flag: "🇿🇦", capital: "Pretoria", continent: "Africa", population: "~60M", currency: "South African Rand", languages: "11 official languages incl. Zulu, Xhosa, Afrikaans, English", nationalFood: "Braai (BBQ) / Bobotie (spiced baked mince)", phraseLanguage: "Zulu", phraseHi: "Sawubona", phraseMorning: "Sawubona (good day)", phraseAfternoon: "Sawubona", funFact: "Three capital cities: Pretoria (executive), Cape Town (legislative), Bloemfontein (judicial)" },
  { name: "South Sudan", flag: "🇸🇸", capital: "Juba", continent: "Africa", population: "~11M", currency: "South Sudanese Pound", languages: "English, Dinka, Nuer", nationalFood: "Asida (sorghum porridge) with meat stew", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon", funFact: "World's youngest country, gained independence in 2011" },
  { name: "Sudan", flag: "🇸🇩", capital: "Khartoum", continent: "Africa", population: "~45M", currency: "Sudanese Pound", languages: "Arabic, English", nationalFood: "Ful medames (stewed fava beans with spices)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)" },
  { name: "Tanzania", flag: "🇹🇿", capital: "Dodoma", continent: "Africa", population: "~63M", currency: "Tanzanian Shilling", languages: "Swahili, English", nationalFood: "Ugali (maize porridge) with nyama choma and sukuma wiki", phraseLanguage: "Swahili", phraseHi: "Habari", phraseMorning: "Habari za asubuhi", phraseAfternoon: "Habari za mchana", funFact: "Home to Kilimanjaro, Africa's highest peak, and the Serengeti" },
  { name: "Togo", flag: "🇹🇬", capital: "Lomé", continent: "Africa", population: "~8.6M", currency: "West African CFA Franc", languages: "French, Ewe, Kabiye", nationalFood: "Fufu (pounded yam) with groundnut soup", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi" },
  { name: "Tunisia", flag: "🇹🇳", capital: "Tunis", continent: "Africa", population: "~12M", currency: "Tunisian Dinar", languages: "Arabic, French", nationalFood: "Couscous with lamb and vegetables / Brik (fried pastry with egg)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)" },
  { name: "Uganda", flag: "🇺🇬", capital: "Kampala", continent: "Africa", population: "~48M", currency: "Ugandan Shilling", languages: "English, Swahili, Luganda", nationalFood: "Matoke (steamed green bananas) with groundnut stew", phraseLanguage: "Swahili", phraseHi: "Habari", phraseMorning: "Habari za asubuhi", phraseAfternoon: "Habari za mchana" },
  { name: "Zambia", flag: "🇿🇲", capital: "Lusaka", continent: "Africa", population: "~19M", currency: "Zambian Kwacha", languages: "English, Bemba, Nyanja", nationalFood: "Nshima (thick maize porridge) with relish and kapenta fish", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Zimbabwe", flag: "🇿🇼", capital: "Harare", continent: "Africa", population: "~16M", currency: "Zimbabwe Gold", languages: "English, Shona, Ndebele", nationalFood: "Sadza (thick maize porridge) with nyama and muriwo", phraseLanguage: "Shona", phraseHi: "Mhoro", phraseMorning: "Mangwanani", phraseAfternoon: "Masikati" },
];

const AMERICAS: C[] = [
  { name: "Antigua and Barbuda", flag: "🇦🇬", capital: "Saint John's", continent: "Americas", population: "~0.1M", currency: "East Caribbean Dollar", languages: "English", nationalFood: "Fungie and pepperpot", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Argentina", flag: "🇦🇷", capital: "Buenos Aires", continent: "Americas", population: "~46M", currency: "Argentine Peso", languages: "Spanish", nationalFood: "Asado (BBQ) / Empanadas / Milanesa", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes", funFact: "Has the widest avenue in the world — Avenida 9 de Julio in Buenos Aires" },
  { name: "Bahamas", flag: "🇧🇸", capital: "Nassau", continent: "Americas", population: "~0.4M", currency: "Bahamian Dollar", languages: "English", nationalFood: "Cracked conch with peas and rice", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Barbados", flag: "🇧🇧", capital: "Bridgetown", continent: "Americas", population: "~0.3M", currency: "Barbadian Dollar", languages: "English", nationalFood: "Cou-cou and flying fish (national dish)", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Belize", flag: "🇧🇿", capital: "Belmopan", continent: "Americas", population: "~0.4M", currency: "Belize Dollar", languages: "English, Spanish, Kriol", nationalFood: "Rice and beans with stewed chicken and plantains", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Bolivia", flag: "🇧🇴", capital: "Sucre", continent: "Americas", population: "~12M", currency: "Bolivian Boliviano", languages: "Spanish, Quechua, Aymara", nationalFood: "Salteñas (baked pastries with meat) / Silpancho (breaded beef)", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes", funFact: "Has the world's highest capital city — La Paz at 3,650m" },
  { name: "Brazil", flag: "🇧🇷", capital: "Brasília", continent: "Americas", population: "~215M", currency: "Brazilian Real", languages: "Portuguese", nationalFood: "Feijoada (black bean and pork stew with rice)", phraseLanguage: "Portuguese", phraseHi: "Olá / Oi", phraseMorning: "Bom dia", phraseAfternoon: "Boa tarde", funFact: "Largest country in South America and home to the Amazon rainforest" },
  { name: "Canada", flag: "🇨🇦", capital: "Ottawa", continent: "Americas", population: "~38M", currency: "Canadian Dollar", languages: "English, French", nationalFood: "Poutine (fries with cheese curds and gravy)", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon", funFact: "Second largest country in the world by total area" },
  { name: "Chile", flag: "🇨🇱", capital: "Santiago", continent: "Americas", population: "~19M", currency: "Chilean Peso", languages: "Spanish", nationalFood: "Empanadas / Cazuela (stew) / Pastel de choclo", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes", funFact: "World's longest country north to south — spans over 4,300km" },
  { name: "Colombia", flag: "🇨🇴", capital: "Bogotá", continent: "Americas", population: "~51M", currency: "Colombian Peso", languages: "Spanish", nationalFood: "Bandeja paisa (beans, rice, meat, egg, plantain platter)", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes", funFact: "Only country in South America with coastline on both Pacific and Atlantic" },
  { name: "Costa Rica", flag: "🇨🇷", capital: "San José", continent: "Americas", population: "~5M", currency: "Costa Rican Colón", languages: "Spanish", nationalFood: "Gallo pinto (rice and beans) — eaten at every meal", phraseLanguage: "Spanish", phraseHi: "Hola / Pura vida", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes", funFact: "Has no standing army — abolished it in 1948" },
  { name: "Cuba", flag: "🇨🇺", capital: "Havana", continent: "Americas", population: "~11M", currency: "Cuban Peso", languages: "Spanish", nationalFood: "Ropa vieja (shredded beef with tomatoes and peppers)", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes" },
  { name: "Dominica", flag: "🇩🇲", capital: "Roseau", continent: "Americas", population: "~0.07M", currency: "East Caribbean Dollar", languages: "English, Antillean Creole", nationalFood: "Mountain chicken (frog legs) / callaloo soup", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Dominican Republic", flag: "🇩🇴", capital: "Santo Domingo", continent: "Americas", population: "~11M", currency: "Dominican Peso", languages: "Spanish", nationalFood: "La Bandera (rice, red beans, meat and salad — 'the flag')", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes" },
  { name: "Ecuador", flag: "🇪🇨", capital: "Quito", continent: "Americas", population: "~18M", currency: "US Dollar", languages: "Spanish, Quechua", nationalFood: "Ceviche / Seco de pollo (braised chicken with rice)", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes", funFact: "The country literally sitting on the equator — Quito is just 25km south" },
  { name: "El Salvador", flag: "🇸🇻", capital: "San Salvador", continent: "Americas", population: "~6.5M", currency: "US Dollar", languages: "Spanish", nationalFood: "Pupusas (thick stuffed corn flatbread)", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes" },
  { name: "Grenada", flag: "🇬🇩", capital: "Saint George's", continent: "Americas", population: "~0.1M", currency: "East Caribbean Dollar", languages: "English", nationalFood: "Oil down (one-pot stew with breadfruit and callaloo — national dish)", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon", funFact: "Known as the 'Spice Isle' — a top producer of nutmeg" },
  { name: "Guatemala", flag: "🇬🇹", capital: "Guatemala City", continent: "Americas", population: "~17M", currency: "Guatemalan Quetzal", languages: "Spanish, 22 Mayan languages", nationalFood: "Pepián (spiced pumpkin seed stew with meat)", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes" },
  { name: "Guyana", flag: "🇬🇾", capital: "Georgetown", continent: "Americas", population: "~0.8M", currency: "Guyanese Dollar", languages: "English", nationalFood: "Pepperpot (slow-cooked spiced meat stew)", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Haiti", flag: "🇭🇹", capital: "Port-au-Prince", continent: "Americas", population: "~11M", currency: "Haitian Gourde", languages: "Haitian Creole, French", nationalFood: "Griot (fried pork) with rice and beans", phraseLanguage: "Haitian Creole", phraseHi: "Bonjou", phraseMorning: "Bonjou (morning greeting)", phraseAfternoon: "Bonswa", funFact: "First Black republic in the world — gained independence from France in 1804" },
  { name: "Honduras", flag: "🇭🇳", capital: "Tegucigalpa", continent: "Americas", population: "~10M", currency: "Honduran Lempira", languages: "Spanish", nationalFood: "Baleadas (flour tortilla with beans, cream and cheese)", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes" },
  { name: "Jamaica", flag: "🇯🇲", capital: "Kingston", continent: "Americas", population: "~3M", currency: "Jamaican Dollar", languages: "English, Jamaican Patois", nationalFood: "Ackee and saltfish (national dish)", phraseLanguage: "Jamaican Patois", phraseHi: "Wah gwaan", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon", funFact: "Birthplace of Bob Marley and reggae music" },
  { name: "Mexico", flag: "🇲🇽", capital: "Mexico City", continent: "Americas", population: "~130M", currency: "Mexican Peso", languages: "Spanish", nationalFood: "Tacos / Mole / Chiles en nogada", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes", funFact: "Mexico City is built on the ruins of the ancient Aztec capital Tenochtitlán" },
  { name: "Nicaragua", flag: "🇳🇮", capital: "Managua", continent: "Americas", population: "~7M", currency: "Nicaraguan Córdoba", languages: "Spanish", nationalFood: "Gallo pinto (rice and beans) / Nacatamal (stuffed corn dough)", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes" },
  { name: "Panama", flag: "🇵🇦", capital: "Panama City", continent: "Americas", population: "~4.4M", currency: "Balboa / US Dollar", languages: "Spanish", nationalFood: "Sancocho (chicken and vegetable stew — national dish)", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes", funFact: "Home to the Panama Canal linking the Pacific and Atlantic Oceans" },
  { name: "Paraguay", flag: "🇵🇾", capital: "Asunción", continent: "Americas", population: "~7.4M", currency: "Paraguayan Guaraní", languages: "Spanish, Guaraní", nationalFood: "Sopa paraguaya (cornbread with cheese and onion)", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes" },
  { name: "Peru", flag: "🇵🇪", capital: "Lima", continent: "Americas", population: "~33M", currency: "Peruvian Sol", languages: "Spanish, Quechua, Aymara", nationalFood: "Ceviche / Lomo saltado / Cuy (guinea pig)", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes", funFact: "Home to Machu Picchu and the ancient Inca civilisation" },
  { name: "Saint Kitts and Nevis", flag: "🇰🇳", capital: "Basseterre", continent: "Americas", population: "~0.05M", currency: "East Caribbean Dollar", languages: "English", nationalFood: "Goat water (spiced goat stew)", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Saint Lucia", flag: "🇱🇨", capital: "Castries", continent: "Americas", population: "~0.18M", currency: "East Caribbean Dollar", languages: "English, Saint Lucian Creole", nationalFood: "Green fig and saltfish (national dish)", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Saint Vincent and the Grenadines", flag: "🇻🇨", capital: "Kingstown", continent: "Americas", population: "~0.11M", currency: "East Caribbean Dollar", languages: "English", nationalFood: "Roasted breadfruit and jackfish", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Suriname", flag: "🇸🇷", capital: "Paramaribo", continent: "Americas", population: "~0.6M", currency: "Surinamese Dollar", languages: "Dutch, Sranan Tongo", nationalFood: "Pom (oven-baked taro root with chicken)", phraseLanguage: "Dutch", phraseHi: "Hoi", phraseMorning: "Goedemorgen", phraseAfternoon: "Goedemiddag" },
  { name: "Trinidad and Tobago", flag: "🇹🇹", capital: "Port of Spain", continent: "Americas", population: "~1.4M", currency: "Trinidad and Tobago Dollar", languages: "English", nationalFood: "Doubles (curried chickpeas in fried bread)", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon", funFact: "Birthplace of the steel pan and calypso music" },
  { name: "United States", flag: "🇺🇸", capital: "Washington D.C.", continent: "Americas", population: "~335M", currency: "US Dollar", languages: "English (de facto)", nationalFood: "Hamburger / Apple pie / BBQ / Thanksgiving turkey", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon", funFact: "Has the world's largest economy by nominal GDP" },
  { name: "Uruguay", flag: "🇺🇾", capital: "Montevideo", continent: "Americas", population: "~3.5M", currency: "Uruguayan Peso", languages: "Spanish", nationalFood: "Asado (BBQ) / Chivito sandwich", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes" },
  { name: "Venezuela", flag: "🇻🇪", capital: "Caracas", continent: "Americas", population: "~28M", currency: "Venezuelan Bolívar", languages: "Spanish", nationalFood: "Pabellón criollo (rice, black beans, shredded beef, plantains)", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes", funFact: "Has the world's largest proven oil reserves" },
];

const ASIA: C[] = [
  { name: "Afghanistan", flag: "🇦🇫", capital: "Kabul", continent: "Asia", population: "~41M", currency: "Afghan Afghani", languages: "Dari, Pashto", nationalFood: "Kabuli pulao (rice with lamb, carrots and raisins)", phraseLanguage: "Dari", phraseHi: "سلام (Salaam)", phraseMorning: "صبح بخیر (Sobh bexeyr)", phraseAfternoon: "روز بخیر (Ruz bexeyr)" },
  { name: "Armenia", flag: "🇦🇲", capital: "Yerevan", continent: "Asia", population: "~3M", currency: "Armenian Dram", languages: "Armenian", nationalFood: "Khorovats (BBQ meat skewers) / Dolma (stuffed grape leaves)", phraseLanguage: "Armenian", phraseHi: "Barev (Բարև)", phraseMorning: "Bari luys (Բարի լույս)", phraseAfternoon: "Bari or (Բարի օր)" },
  { name: "Azerbaijan", flag: "🇦🇿", capital: "Baku", continent: "Asia", population: "~10M", currency: "Azerbaijani Manat", languages: "Azerbaijani", nationalFood: "Plov (saffron rice with lamb) / Dolma", phraseLanguage: "Azerbaijani", phraseHi: "Salam", phraseMorning: "Sabahınız xeyir", phraseAfternoon: "Günortanız xeyir", funFact: "First Muslim-majority country to have opera, theatre and a democratic republic" },
  { name: "Bangladesh", flag: "🇧🇩", capital: "Dhaka", continent: "Asia", population: "~170M", currency: "Bangladeshi Taka", languages: "Bengali", nationalFood: "Hilsa fish curry / Rice with various curries", phraseLanguage: "Bengali", phraseHi: "আস-সালামু আলাইকুম (As-salamu alaykum)", phraseMorning: "শুভ সকাল (Shubho shokal)", phraseAfternoon: "শুভ দুপুর (Shubho dupur)" },
  { name: "Bhutan", flag: "🇧🇹", capital: "Thimphu", continent: "Asia", population: "~0.8M", currency: "Bhutanese Ngultrum", languages: "Dzongkha", nationalFood: "Ema datshi (chilli and cheese stew — national dish)", phraseLanguage: "Dzongkha", phraseHi: "Kuzu zangpo la", phraseMorning: "Choe ga deleg", phraseAfternoon: "Choe ga deleg", funFact: "Measures prosperity by Gross National Happiness instead of GDP" },
  { name: "Brunei", flag: "🇧🇳", capital: "Bandar Seri Begawan", continent: "Asia", population: "~0.45M", currency: "Brunei Dollar", languages: "Malay, English", nationalFood: "Ambuyat (glutinous sago dish eaten with bamboo skewers)", phraseLanguage: "Malay", phraseHi: "Hai", phraseMorning: "Selamat pagi", phraseAfternoon: "Selamat tengah hari" },
  { name: "Cambodia", flag: "🇰🇭", capital: "Phnom Penh", continent: "Asia", population: "~17M", currency: "Cambodian Riel", languages: "Khmer", nationalFood: "Fish amok (steamed fish in coconut curry — national dish)", phraseLanguage: "Khmer", phraseHi: "ជំរាបសួរ (Chumreap suor)", phraseMorning: "អរុណសួស្តី (Arun suosdei)", phraseAfternoon: "ទិវាសួស្តី (Tivea suosdei)", funFact: "Home to Angkor Wat, the largest religious monument in the world" },
  { name: "China", flag: "🇨🇳", capital: "Beijing", continent: "Asia", population: "~1.4B", currency: "Chinese Yuan (Renminbi)", languages: "Mandarin", nationalFood: "Peking duck / Dim sum / Kung pao chicken", phraseLanguage: "Mandarin", phraseHi: "你好 (Nǐ hǎo)", phraseMorning: "早上好 (Zǎoshang hǎo)", phraseAfternoon: "下午好 (Xiàwǔ hǎo)", funFact: "Has the world's oldest continuous civilisation — over 4,000 years of recorded history" },
  { name: "Georgia", flag: "🇬🇪", capital: "Tbilisi", continent: "Asia", population: "~4M", currency: "Georgian Lari", languages: "Georgian", nationalFood: "Khinkali (soup dumplings) / Khachapuri (cheese-filled bread)", phraseLanguage: "Georgian", phraseHi: "გამარჯობა (Gamarjoba)", phraseMorning: "დილა მშვიდობისა (Dila mshvidobisa)", phraseAfternoon: "შუადღე მშვიდობისა (Shuadghe mshvidobisa)" },
  { name: "India", flag: "🇮🇳", capital: "New Delhi", continent: "Asia", population: "~1.43B", currency: "Indian Rupee", languages: "Hindi, English (22 official languages)", nationalFood: "Biryani / Dal / Butter chicken / Samosa", phraseLanguage: "Hindi", phraseHi: "नमस्ते (Namaste)", phraseMorning: "सुप्रभात (Suprabhat)", phraseAfternoon: "नमस्कार (Namaskar)", funFact: "World's most populous country and largest democracy" },
  { name: "Indonesia", flag: "🇮🇩", capital: "Jakarta", continent: "Asia", population: "~277M", currency: "Indonesian Rupiah", languages: "Indonesian (Bahasa)", nationalFood: "Nasi goreng (fried rice) / Rendang (slow-cooked beef)", phraseLanguage: "Indonesian", phraseHi: "Halo", phraseMorning: "Selamat pagi", phraseAfternoon: "Selamat siang", funFact: "World's largest archipelago — over 17,000 islands" },
  { name: "Japan", flag: "🇯🇵", capital: "Tokyo", continent: "Asia", population: "~125M", currency: "Japanese Yen", languages: "Japanese", nationalFood: "Sushi / Ramen / Tempura / Miso soup", phraseLanguage: "Japanese", phraseHi: "こんにちは (Konnichiwa)", phraseMorning: "おはようございます (Ohayou gozaimasu)", phraseAfternoon: "こんにちは (Konnichiwa)", funFact: "Has the world's third largest economy and the highest life expectancy" },
  { name: "Kazakhstan", flag: "🇰🇿", capital: "Astana", continent: "Asia", population: "~19M", currency: "Kazakhstani Tenge", languages: "Kazakh, Russian", nationalFood: "Beshbarmak (boiled meat over flat noodles — national dish)", phraseLanguage: "Kazakh", phraseHi: "Сәлем (Sälem)", phraseMorning: "Қайырлы таң (Qayyrly tañ)", phraseAfternoon: "Қайырлы күн (Qayyrly kün)", funFact: "Largest landlocked country in the world" },
  { name: "Kyrgyzstan", flag: "🇰🇬", capital: "Bishkek", continent: "Asia", population: "~6.8M", currency: "Kyrgyzstani Som", languages: "Kyrgyz, Russian", nationalFood: "Beshbarmak (boiled meat with noodles)", phraseLanguage: "Kyrgyz", phraseHi: "Салам (Salam)", phraseMorning: "Куттулуу эртең (Kuttuluu erteñ)", phraseAfternoon: "Куттулуу күн (Kuttuluu kün)" },
  { name: "Laos", flag: "🇱🇦", capital: "Vientiane", continent: "Asia", population: "~7.4M", currency: "Lao Kip", languages: "Lao", nationalFood: "Laap (minced meat salad with herbs) / Sticky rice", phraseLanguage: "Lao", phraseHi: "ສະບາຍດີ (Sabaidee)", phraseMorning: "ສະບາຍດີຕອນເຊົ້າ (Sabaidee ton sao)", phraseAfternoon: "ສະບາຍດີຕອນບ່າຍ (Sabaidee ton bai)" },
  { name: "Malaysia", flag: "🇲🇾", capital: "Kuala Lumpur", continent: "Asia", population: "~33M", currency: "Malaysian Ringgit", languages: "Malay, English, Mandarin, Tamil", nationalFood: "Nasi lemak (coconut milk rice with sambal — national dish)", phraseLanguage: "Malay", phraseHi: "Hai", phraseMorning: "Selamat pagi", phraseAfternoon: "Selamat tengah hari", funFact: "Home to the Petronas Twin Towers — world's tallest twin buildings" },
  { name: "Maldives", flag: "🇲🇻", capital: "Malé", continent: "Asia", population: "~0.52M", currency: "Maldivian Rufiyaa", languages: "Dhivehi", nationalFood: "Mas huni (tuna with coconut and lime — national dish)", phraseLanguage: "Dhivehi", phraseHi: "ހެލޯ (Hello)", phraseMorning: "ހެޔޮ ހެނދުނެއް (Heyyo hendhunek)", phraseAfternoon: "ހެޔޮ ދުވަހެއް (Heyyo duvahek)", funFact: "The flattest country on Earth — average elevation just 1.5m above sea level" },
  { name: "Mongolia", flag: "🇲🇳", capital: "Ulaanbaatar", continent: "Asia", population: "~3.4M", currency: "Mongolian Tögrög", languages: "Mongolian", nationalFood: "Khorkhog (goat cooked with hot stones) / Buuz (steamed dumplings)", phraseLanguage: "Mongolian", phraseHi: "Сайн уу (Sain uu)", phraseMorning: "Өглөөний мэнд (Öglöönii mend)", phraseAfternoon: "Өдрийн мэнд (Ödriin mend)", funFact: "Has the world's lowest population density of any country" },
  { name: "Myanmar", flag: "🇲🇲", capital: "Naypyidaw", continent: "Asia", population: "~54M", currency: "Myanmar Kyat", languages: "Burmese", nationalFood: "Mohinga (fish noodle soup — national dish)", phraseLanguage: "Burmese", phraseHi: "မင်္ဂလာပါ (Mingalaba)", phraseMorning: "မင်္ဂလာနံနက်ခင်း (Mingala nankhechin)", phraseAfternoon: "မင်္ဂလာနေ့ခင်း (Mingala neykhechin)" },
  { name: "Nepal", flag: "🇳🇵", capital: "Kathmandu", continent: "Asia", population: "~30M", currency: "Nepalese Rupee", languages: "Nepali", nationalFood: "Dal bhat (lentil soup with rice and vegetable curry)", phraseLanguage: "Nepali", phraseHi: "नमस्ते (Namaste)", phraseMorning: "शुभ प्रभात (Shubha prabhat)", phraseAfternoon: "शुभ दिन (Shubha din)", funFact: "Home to eight of the world's ten highest mountains including Everest" },
  { name: "North Korea", flag: "🇰🇵", capital: "Pyongyang", continent: "Asia", population: "~26M", currency: "North Korean Won", languages: "Korean", nationalFood: "Pyongyang cold noodles / Kimchi / Dog meat stew", phraseLanguage: "Korean", phraseHi: "안녕하세요 (Annyeonghaseyo)", phraseMorning: "좋은 아침 (Joeun achim)", phraseAfternoon: "안녕하세요 (Annyeonghaseyo)" },
  { name: "Pakistan", flag: "🇵🇰", capital: "Islamabad", continent: "Asia", population: "~230M", currency: "Pakistani Rupee", languages: "Urdu, English", nationalFood: "Biryani / Nihari (slow-cooked beef stew)", phraseLanguage: "Urdu", phraseHi: "السلام علیکم (Assalamu alaikum)", phraseMorning: "صبح بخیر (Subah bakhair)", phraseAfternoon: "دوپہر بخیر (Dopahar bakhair)", funFact: "Home to K2 — the world's second highest mountain" },
  { name: "Philippines", flag: "🇵🇭", capital: "Manila", continent: "Asia", population: "~113M", currency: "Philippine Peso", languages: "Filipino, English", nationalFood: "Adobo (braised chicken or pork in soy and vinegar)", phraseLanguage: "Filipino", phraseHi: "Kumusta", phraseMorning: "Magandang umaga", phraseAfternoon: "Magandang tanghali", funFact: "Archipelago of over 7,000 islands" },
  { name: "Singapore", flag: "🇸🇬", capital: "Singapore", continent: "Asia", population: "~5.9M", currency: "Singapore Dollar", languages: "English, Malay, Mandarin, Tamil", nationalFood: "Chicken rice (Hainanese style — national dish)", phraseLanguage: "English", phraseHi: "Hi / Lah", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon", funFact: "City-state with one of the highest GDPs per capita in the world" },
  { name: "South Korea", flag: "🇰🇷", capital: "Seoul", continent: "Asia", population: "~52M", currency: "South Korean Won", languages: "Korean", nationalFood: "Kimchi / Bibimbap / Korean BBQ / Tteokbokki", phraseLanguage: "Korean", phraseHi: "안녕하세요 (Annyeonghaseyo)", phraseMorning: "좋은 아침이에요 (Joeun achimieyo)", phraseAfternoon: "좋은 오후에요 (Joeun ohueyo)", funFact: "Has the fastest internet speeds in the world" },
  { name: "Sri Lanka", flag: "🇱🇰", capital: "Sri Jayawardenepura Kotte", continent: "Asia", population: "~22M", currency: "Sri Lankan Rupee", languages: "Sinhala, Tamil", nationalFood: "Rice and curry / Hoppers (bowl-shaped coconut pancakes)", phraseLanguage: "Sinhala", phraseHi: "ආයුබෝවන් (Ayubowan)", phraseMorning: "සුබ උදෑසනක් (Suba udaesanak)", phraseAfternoon: "සුබ දහවලක් (Suba dahawelak)" },
  { name: "Taiwan", flag: "🇹🇼", capital: "Taipei", continent: "Asia", population: "~23M", currency: "New Taiwan Dollar", languages: "Mandarin", nationalFood: "Beef noodle soup / Scallion pancakes / Oyster omelette", phraseLanguage: "Mandarin", phraseHi: "你好 (Nǐ hǎo)", phraseMorning: "早安 (Zǎo ān)", phraseAfternoon: "午安 (Wǔ ān)", funFact: "Invented bubble tea — now enjoyed globally" },
  { name: "Tajikistan", flag: "🇹🇯", capital: "Dushanbe", continent: "Asia", population: "~10M", currency: "Tajikistani Somoni", languages: "Tajik, Russian", nationalFood: "Qurutob (flatbread soaked in sour milk with onions)", phraseLanguage: "Tajik", phraseHi: "Салом (Salom)", phraseMorning: "Субҳ бахайр (Subh baxayr)", phraseAfternoon: "Рӯз бахайр (Rüz baxayr)" },
  { name: "Thailand", flag: "🇹🇭", capital: "Bangkok", continent: "Asia", population: "~72M", currency: "Thai Baht", languages: "Thai", nationalFood: "Pad thai / Tom yum soup / Green curry / Som tam", phraseLanguage: "Thai", phraseHi: "สวัสดี (Sawasdee)", phraseMorning: "สวัสดีตอนเช้า (Sawasdee ton chao)", phraseAfternoon: "สวัสดีตอนบ่าย (Sawasdee ton baay)", funFact: "Only Southeast Asian country never colonised by a European power" },
  { name: "Timor-Leste", flag: "🇹🇱", capital: "Dili", continent: "Asia", population: "~1.3M", currency: "US Dollar", languages: "Tetum, Portuguese", nationalFood: "Ikan sabuko (smoked tuna with coconut milk and chilli)", phraseLanguage: "Tetum", phraseHi: "Olá", phraseMorning: "Bondia", phraseAfternoon: "Botarde", funFact: "One of the world's youngest countries — gained independence in 2002" },
  { name: "Turkmenistan", flag: "🇹🇲", capital: "Ashgabat", continent: "Asia", population: "~6M", currency: "Turkmenistani Manat", languages: "Turkmen, Russian", nationalFood: "Plov (rice with lamb and carrots — national dish)", phraseLanguage: "Turkmen", phraseHi: "Salam", phraseMorning: "Ertiriňiz haýyrly bolsun", phraseAfternoon: "Günüňiz haýyrly bolsun", funFact: "Has the Darvaza gas crater — 'Door to Hell' — burning since 1971" },
  { name: "Uzbekistan", flag: "🇺🇿", capital: "Tashkent", continent: "Asia", population: "~36M", currency: "Uzbekistani Som", languages: "Uzbek", nationalFood: "Plov (rice with lamb, onions and carrots — national dish)", phraseLanguage: "Uzbek", phraseHi: "Assalomu alaykum", phraseMorning: "Xayrli tong", phraseAfternoon: "Xayrli kun", funFact: "Samarkand was a key city on the ancient Silk Road" },
  { name: "Vietnam", flag: "🇻🇳", capital: "Hanoi", continent: "Asia", population: "~98M", currency: "Vietnamese Dong", languages: "Vietnamese", nationalFood: "Phở (noodle soup) / Bánh mì / Gỏi cuốn (spring rolls)", phraseLanguage: "Vietnamese", phraseHi: "Xin chào", phraseMorning: "Chào buổi sáng", phraseAfternoon: "Chào buổi chiều", funFact: "One of the fastest growing economies in Southeast Asia" },
];

const MIDDLE_EAST: C[] = [
  { name: "Bahrain", flag: "🇧🇭", capital: "Manama", continent: "Middle East", population: "~1.5M", currency: "Bahraini Dinar", languages: "Arabic", nationalFood: "Machboos (spiced rice with fish or lamb)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)" },
  { name: "Cyprus", flag: "🇨🇾", capital: "Nicosia", continent: "Middle East", population: "~1.2M", currency: "Euro", languages: "Greek, Turkish", nationalFood: "Souvlaki / Meze (shared small dishes)", phraseLanguage: "Greek", phraseHi: "Γεια σας (Yia sas)", phraseMorning: "Καλημέρα (Kalimera)", phraseAfternoon: "Καλησπέρα (Kalispera)" },
  { name: "Iran", flag: "🇮🇷", capital: "Tehran", continent: "Middle East", population: "~87M", currency: "Iranian Rial", languages: "Persian (Farsi)", nationalFood: "Ghormeh sabzi (herb and kidney bean stew) / Kabab", phraseLanguage: "Persian (Farsi)", phraseHi: "سلام (Salâm)", phraseMorning: "صبح بخیر (Sobh bexeyr)", phraseAfternoon: "بعد از ظهر بخیر (Ba'd az zohr bexeyr)", funFact: "Home to one of the world's oldest civilisations — Persia dates back 2,500 years" },
  { name: "Iraq", flag: "🇮🇶", capital: "Baghdad", continent: "Middle East", population: "~42M", currency: "Iraqi Dinar", languages: "Arabic, Kurdish", nationalFood: "Masgouf (grilled Tigris carp — national dish) / Dolma", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)", funFact: "Mesopotamia — 'cradle of civilisation' — is present-day Iraq" },
  { name: "Israel", flag: "🇮🇱", capital: "Jerusalem", continent: "Middle East", population: "~9.7M", currency: "Israeli New Shekel", languages: "Hebrew, Arabic", nationalFood: "Falafel / Shakshuka / Hummus / Sabich", phraseLanguage: "Hebrew", phraseHi: "שלום (Shalom)", phraseMorning: "בוקר טוב (Boker tov)", phraseAfternoon: "צהריים טובים (Tzohorayim tovim)" },
  { name: "Jordan", flag: "🇯🇴", capital: "Amman", continent: "Middle East", population: "~10M", currency: "Jordanian Dinar", languages: "Arabic", nationalFood: "Mansaf (lamb in fermented yoghurt sauce with rice — national dish)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)", funFact: "Home to Petra — the ancient city carved into rose-red rock" },
  { name: "Kuwait", flag: "🇰🇼", capital: "Kuwait City", continent: "Middle East", population: "~4.3M", currency: "Kuwaiti Dinar", languages: "Arabic", nationalFood: "Machboos (spiced rice with lamb or shrimp)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)", funFact: "Kuwaiti Dinar is the world's highest-valued currency" },
  { name: "Lebanon", flag: "🇱🇧", capital: "Beirut", continent: "Middle East", population: "~5.5M", currency: "Lebanese Pound", languages: "Arabic, French", nationalFood: "Kibbeh / Meze spread / Tabbouleh", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)", funFact: "Beirut was once known as the 'Paris of the Middle East'" },
  { name: "Oman", flag: "🇴🇲", capital: "Muscat", continent: "Middle East", population: "~4.5M", currency: "Omani Rial", languages: "Arabic", nationalFood: "Shuwa (slow-cooked lamb in underground pit) / Majboos", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)" },
  { name: "Palestine", flag: "🇵🇸", capital: "Ramallah", continent: "Middle East", population: "~5.4M", currency: "Israeli New Shekel / Jordanian Dinar", languages: "Arabic", nationalFood: "Musakhan (chicken with caramelised onions and sumac on flatbread)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)" },
  { name: "Qatar", flag: "🇶🇦", capital: "Doha", continent: "Middle East", population: "~2.9M", currency: "Qatari Riyal", languages: "Arabic", nationalFood: "Machboos (spiced rice with meat) / Harees (wheat and meat porridge)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)", funFact: "Highest GDP per capita in the world" },
  { name: "Saudi Arabia", flag: "🇸🇦", capital: "Riyadh", continent: "Middle East", population: "~36M", currency: "Saudi Riyal", languages: "Arabic", nationalFood: "Kabsa (aromatic spiced rice with meat — national dish)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)", funFact: "Largest country in the Middle East and birthplace of Islam" },
  { name: "Syria", flag: "🇸🇾", capital: "Damascus", continent: "Middle East", population: "~21M", currency: "Syrian Pound", languages: "Arabic", nationalFood: "Kibbeh / Fatteh / Falafel / Baklava", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)", funFact: "Damascus is one of the oldest continuously inhabited cities in the world" },
  { name: "Turkey", flag: "🇹🇷", capital: "Ankara", continent: "Middle East", population: "~85M", currency: "Turkish Lira", languages: "Turkish", nationalFood: "Kebab / Baklava / Menemen / Turkish breakfast (kahvaltı)", phraseLanguage: "Turkish", phraseHi: "Merhaba", phraseMorning: "Günaydın", phraseAfternoon: "İyi öğleden sonralar", funFact: "Transcontinental — spans both Europe and Asia, with Istanbul straddling the Bosphorus" },
  { name: "United Arab Emirates", flag: "🇦🇪", capital: "Abu Dhabi", continent: "Middle East", population: "~9.9M", currency: "UAE Dirham", languages: "Arabic", nationalFood: "Machboos / Luqaimat (sweet honey dumplings)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)", funFact: "Dubai has the world's tallest building — the Burj Khalifa at 828m" },
  { name: "Yemen", flag: "🇾🇪", capital: "Sana'a", continent: "Middle East", population: "~34M", currency: "Yemeni Rial", languages: "Arabic", nationalFood: "Mandi (slow-cooked lamb and rice) / Saltah (meat stew)", phraseLanguage: "Arabic", phraseHi: "مرحبا (Marhaba)", phraseMorning: "صباح الخير (Sabah el-kheir)", phraseAfternoon: "مساء الخير (Masa el-kheir)", funFact: "Sana'a's old city is a UNESCO World Heritage Site with tower houses up to 9 storeys" },
];

const EUROPE: C[] = [
  { name: "Albania", flag: "🇦🇱", capital: "Tirana", continent: "Europe", population: "~2.8M", currency: "Albanian Lek", languages: "Albanian", nationalFood: "Tavë kosi (lamb and rice baked with yoghurt)", phraseLanguage: "Albanian", phraseHi: "Përshëndetje", phraseMorning: "Mirëmëngjes", phraseAfternoon: "Mirëdita" },
  { name: "Andorra", flag: "🇦🇩", capital: "Andorra la Vella", continent: "Europe", population: "~0.08M", currency: "Euro", languages: "Catalan", nationalFood: "Escudella (meat and vegetable stew)", phraseLanguage: "Catalan", phraseHi: "Hola", phraseMorning: "Bon dia", phraseAfternoon: "Bona tarda", funFact: "Smallest country in the world with co-princes as heads of state" },
  { name: "Austria", flag: "🇦🇹", capital: "Vienna", continent: "Europe", population: "~9M", currency: "Euro", languages: "German", nationalFood: "Wiener Schnitzel / Apfelstrudel / Sachertorte", phraseLanguage: "German", phraseHi: "Hallo / Grüß Gott", phraseMorning: "Guten Morgen", phraseAfternoon: "Guten Nachmittag" },
  { name: "Belarus", flag: "🇧🇾", capital: "Minsk", continent: "Europe", population: "~9.4M", currency: "Belarusian Ruble", languages: "Belarusian, Russian", nationalFood: "Draniki (potato pancakes) / Machanka (pork stew)", phraseLanguage: "Belarusian", phraseHi: "Вітаю (Vitayu)", phraseMorning: "Добрай раніцы (Dobray ranitsy)", phraseAfternoon: "Добры дзень (Dobry dzen)" },
  { name: "Belgium", flag: "🇧🇪", capital: "Brussels", continent: "Europe", population: "~11.6M", currency: "Euro", languages: "Dutch, French, German", nationalFood: "Moules-frites (mussels and fries) / Waffles / Belgian chocolate", phraseLanguage: "French", phraseHi: "Bonjour / Hallo", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi", funFact: "Headquarters of the EU and NATO are both in Brussels" },
  { name: "Bosnia and Herzegovina", flag: "🇧🇦", capital: "Sarajevo", continent: "Europe", population: "~3.3M", currency: "Bosnia and Herzegovina Convertible Mark", languages: "Bosnian, Serbian, Croatian", nationalFood: "Ćevapi (grilled minced meat with flatbread and onions)", phraseLanguage: "Bosnian", phraseHi: "Zdravo", phraseMorning: "Dobro jutro", phraseAfternoon: "Dobar dan" },
  { name: "Bulgaria", flag: "🇧🇬", capital: "Sofia", continent: "Europe", population: "~6.5M", currency: "Bulgarian Lev", languages: "Bulgarian", nationalFood: "Banitsa (cheese-filled filo pastry) / Shopska salad", phraseLanguage: "Bulgarian", phraseHi: "Здравейте (Zdraveyte)", phraseMorning: "Добро утро (Dobro utro)", phraseAfternoon: "Добър ден (Dobar den)" },
  { name: "Croatia", flag: "🇭🇷", capital: "Zagreb", continent: "Europe", population: "~4M", currency: "Euro", languages: "Croatian", nationalFood: "Peka (slow-cooked meat under iron bell) / Crni rižot (black squid ink risotto)", phraseLanguage: "Croatian", phraseHi: "Zdravo", phraseMorning: "Dobro jutro", phraseAfternoon: "Dobar dan" },
  { name: "Czech Republic", flag: "🇨🇿", capital: "Prague", continent: "Europe", population: "~10.9M", currency: "Czech Koruna", languages: "Czech", nationalFood: "Svíčková (beef sirloin with cream sauce) / Trdelník", phraseLanguage: "Czech", phraseHi: "Ahoj", phraseMorning: "Dobré ráno", phraseAfternoon: "Dobré odpoledne", funFact: "Prague is home to the largest ancient castle complex in the world" },
  { name: "Denmark", flag: "🇩🇰", capital: "Copenhagen", continent: "Europe", population: "~5.9M", currency: "Danish Krone", languages: "Danish", nationalFood: "Smørrebrød (open-faced rye bread sandwiches) / Frikadeller", phraseLanguage: "Danish", phraseHi: "Hej", phraseMorning: "God morgen", phraseAfternoon: "God eftermiddag" },
  { name: "Estonia", flag: "🇪🇪", capital: "Tallinn", continent: "Europe", population: "~1.3M", currency: "Euro", languages: "Estonian", nationalFood: "Verivorst (blood sausage) / Mulgipuder (potato and barley porridge)", phraseLanguage: "Estonian", phraseHi: "Tere", phraseMorning: "Tere hommikust", phraseAfternoon: "Tere päevast", funFact: "One of the most digitally advanced societies — first country to vote online in 2005" },
  { name: "Finland", flag: "🇫🇮", capital: "Helsinki", continent: "Europe", population: "~5.5M", currency: "Euro", languages: "Finnish, Swedish", nationalFood: "Karjalanpiirakka (Karelian rice pasties) / Salmiak (salty liquorice)", phraseLanguage: "Finnish", phraseHi: "Hei", phraseMorning: "Hyvää huomenta", phraseAfternoon: "Hyvää päivää", funFact: "Consistently ranked the world's happiest country" },
  { name: "France", flag: "🇫🇷", capital: "Paris", continent: "Europe", population: "~68M", currency: "Euro", languages: "French", nationalFood: "Coq au vin / Croissant / Bouillabaisse / Baguette", phraseLanguage: "French", phraseHi: "Bonjour / Salut", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi", funFact: "Most visited country in the world with ~90 million tourists per year" },
  { name: "Germany", flag: "🇩🇪", capital: "Berlin", continent: "Europe", population: "~84M", currency: "Euro", languages: "German", nationalFood: "Bratwurst / Sauerkraut / Pretzels / Schwarzwälder Kirschtorte", phraseLanguage: "German", phraseHi: "Hallo", phraseMorning: "Guten Morgen", phraseAfternoon: "Guten Nachmittag", funFact: "Has the largest economy in Europe" },
  { name: "Greece", flag: "🇬🇷", capital: "Athens", continent: "Europe", population: "~10.7M", currency: "Euro", languages: "Greek", nationalFood: "Moussaka / Souvlaki / Spanakopita / Baklava", phraseLanguage: "Greek", phraseHi: "Γεια σας (Yia sas)", phraseMorning: "Καλημέρα (Kalimera)", phraseAfternoon: "Καλησπέρα (Kalispera)", funFact: "Birthplace of democracy, philosophy, and the Olympic Games" },
  { name: "Hungary", flag: "🇭🇺", capital: "Budapest", continent: "Europe", population: "~9.7M", currency: "Hungarian Forint", languages: "Hungarian", nationalFood: "Goulash (beef paprika stew) / Lángos (deep-fried flatbread)", phraseLanguage: "Hungarian", phraseHi: "Helló / Szia", phraseMorning: "Jó reggelt", phraseAfternoon: "Jó napot" },
  { name: "Iceland", flag: "🇮🇸", capital: "Reykjavík", continent: "Europe", population: "~0.37M", currency: "Icelandic Króna", languages: "Icelandic", nationalFood: "Skyr (thick Icelandic dairy) / Plokkfiskur (fish stew)", phraseLanguage: "Icelandic", phraseHi: "Halló", phraseMorning: "Góðan daginn", phraseAfternoon: "Góðan dag", funFact: "Land of fire and ice — has active volcanoes and year-round glaciers" },
  { name: "Ireland", flag: "🇮🇪", capital: "Dublin", continent: "Europe", population: "~5.1M", currency: "Euro", languages: "English, Irish (Gaeilge)", nationalFood: "Irish stew (lamb and potato) / Full Irish breakfast / Soda bread", phraseLanguage: "Irish", phraseHi: "Dia duit (Hello in Irish)", phraseMorning: "Maidin mhaith", phraseAfternoon: "Tráthnóna maith" },
  { name: "Italy", flag: "🇮🇹", capital: "Rome", continent: "Europe", population: "~59M", currency: "Euro", languages: "Italian", nationalFood: "Pizza Napoletana / Pasta / Gelato / Risotto", phraseLanguage: "Italian", phraseHi: "Ciao", phraseMorning: "Buongiorno", phraseAfternoon: "Buon pomeriggio", funFact: "Has the most UNESCO World Heritage Sites of any country" },
  { name: "Kosovo", flag: "🇽🇰", capital: "Pristina", continent: "Europe", population: "~1.8M", currency: "Euro", languages: "Albanian, Serbian", nationalFood: "Flia (layered baked pancake with clotted cream)", phraseLanguage: "Albanian", phraseHi: "Përshëndetje", phraseMorning: "Mirëmëngjes", phraseAfternoon: "Mirëdita", funFact: "One of Europe's youngest countries — declared independence in 2008" },
  { name: "Latvia", flag: "🇱🇻", capital: "Riga", continent: "Europe", population: "~1.8M", currency: "Euro", languages: "Latvian", nationalFood: "Rupjmaize (dark rye bread) / Grey peas with bacon", phraseLanguage: "Latvian", phraseHi: "Sveiki", phraseMorning: "Labrīt", phraseAfternoon: "Labdien" },
  { name: "Liechtenstein", flag: "🇱🇮", capital: "Vaduz", continent: "Europe", population: "~0.04M", currency: "Swiss Franc", languages: "German", nationalFood: "Käsknöpfle (cheese spätzle with onions)", phraseLanguage: "German", phraseHi: "Hallo", phraseMorning: "Guten Morgen", phraseAfternoon: "Guten Nachmittag", funFact: "One of only two doubly landlocked countries in the world" },
  { name: "Lithuania", flag: "🇱🇹", capital: "Vilnius", continent: "Europe", population: "~2.8M", currency: "Euro", languages: "Lithuanian", nationalFood: "Cepelinai (potato dumplings stuffed with meat)", phraseLanguage: "Lithuanian", phraseHi: "Sveiki", phraseMorning: "Labas rytas", phraseAfternoon: "Laba diena" },
  { name: "Luxembourg", flag: "🇱🇺", capital: "Luxembourg City", continent: "Europe", population: "~0.65M", currency: "Euro", languages: "Luxembourgish, French, German", nationalFood: "Judd mat Gaardebounen (smoked pork collar with broad beans)", phraseLanguage: "Luxembourgish", phraseHi: "Moien", phraseMorning: "Gudde Muorgen", phraseAfternoon: "Gudde Mëtteg", funFact: "Has the highest GDP per capita in the EU" },
  { name: "Malta", flag: "🇲🇹", capital: "Valletta", continent: "Europe", population: "~0.54M", currency: "Euro", languages: "Maltese, English", nationalFood: "Ftira (Maltese sandwich) / Fenek moqli (fried rabbit — national dish)", phraseLanguage: "Maltese", phraseHi: "Bonġu / Hej", phraseMorning: "Bonġu (Good morning)", phraseAfternoon: "Wara nofs in-nhar it-tajjeb" },
  { name: "Moldova", flag: "🇲🇩", capital: "Chișinău", continent: "Europe", population: "~2.6M", currency: "Moldovan Leu", languages: "Moldovan (Romanian)", nationalFood: "Mămăligă (cornmeal porridge) / Plăcintă (layered pastry)", phraseLanguage: "Romanian", phraseHi: "Bună ziua", phraseMorning: "Bună dimineața", phraseAfternoon: "Bună ziua" },
  { name: "Monaco", flag: "🇲🇨", capital: "Monaco", continent: "Europe", population: "~0.04M", currency: "Euro", languages: "French", nationalFood: "Barbagiuan (fried pastry with ricotta and spinach)", phraseLanguage: "French", phraseHi: "Bonjour", phraseMorning: "Bonjour", phraseAfternoon: "Bon après-midi", funFact: "Second smallest country in the world — smaller than New York's Central Park" },
  { name: "Montenegro", flag: "🇲🇪", capital: "Podgorica", continent: "Europe", population: "~0.62M", currency: "Euro", languages: "Montenegrin", nationalFood: "Kačamak (potato polenta with cheese) / Ćevapi", phraseLanguage: "Montenegrin", phraseHi: "Zdravo", phraseMorning: "Dobro jutro", phraseAfternoon: "Dobar dan" },
  { name: "Netherlands", flag: "🇳🇱", capital: "Amsterdam", continent: "Europe", population: "~17.9M", currency: "Euro", languages: "Dutch", nationalFood: "Stroopwafel / Bitterballen / Raw herring", phraseLanguage: "Dutch", phraseHi: "Hoi / Hallo", phraseMorning: "Goedemorgen", phraseAfternoon: "Goedemiddag" },
  { name: "North Macedonia", flag: "🇲🇰", capital: "Skopje", continent: "Europe", population: "~2.1M", currency: "Macedonian Denar", languages: "Macedonian, Albanian", nationalFood: "Tavče gravče (beans baked in clay pot — national dish)", phraseLanguage: "Macedonian", phraseHi: "Здраво (Zdravo)", phraseMorning: "Добро утро (Dobro utro)", phraseAfternoon: "Добар ден (Dobar den)" },
  { name: "Norway", flag: "🇳🇴", capital: "Oslo", continent: "Europe", population: "~5.4M", currency: "Norwegian Krone", languages: "Norwegian", nationalFood: "Fårikål (lamb and cabbage stew — national dish) / Lutefisk", phraseLanguage: "Norwegian", phraseHi: "Hei", phraseMorning: "God morgen", phraseAfternoon: "God ettermiddag", funFact: "Has one of the highest standards of living and the largest sovereign wealth fund" },
  { name: "Poland", flag: "🇵🇱", capital: "Warsaw", continent: "Europe", population: "~38M", currency: "Polish Złoty", languages: "Polish", nationalFood: "Pierogi (stuffed dumplings) / Bigos (hunter's stew) / Żurek", phraseLanguage: "Polish", phraseHi: "Cześć / Dzień dobry", phraseMorning: "Dzień dobry", phraseAfternoon: "Dzień dobry" },
  { name: "Portugal", flag: "🇵🇹", capital: "Lisbon", continent: "Europe", population: "~10.3M", currency: "Euro", languages: "Portuguese", nationalFood: "Bacalhau (salt cod) / Pastéis de nata (custard tarts)", phraseLanguage: "Portuguese", phraseHi: "Olá", phraseMorning: "Bom dia", phraseAfternoon: "Boa tarde", funFact: "Once had the world's largest empire spanning five continents" },
  { name: "Romania", flag: "🇷🇴", capital: "Bucharest", continent: "Europe", population: "~19M", currency: "Romanian Leu", languages: "Romanian", nationalFood: "Sarmale (cabbage stuffed with pork and rice) / Mămăligă", phraseLanguage: "Romanian", phraseHi: "Bună ziua / Salut", phraseMorning: "Bună dimineața", phraseAfternoon: "Bună ziua" },
  { name: "Russia", flag: "🇷🇺", capital: "Moscow", continent: "Europe", population: "~145M", currency: "Russian Ruble", languages: "Russian", nationalFood: "Borscht / Pelmeni (dumplings) / Blini (pancakes)", phraseLanguage: "Russian", phraseHi: "Привет (Privet)", phraseMorning: "Доброе утро (Dobroye utro)", phraseAfternoon: "Добрый день (Dobryy den)", funFact: "Largest country in the world by area — spans 11 time zones" },
  { name: "San Marino", flag: "🇸🇲", capital: "San Marino", continent: "Europe", population: "~0.034M", currency: "Euro", languages: "Italian", nationalFood: "Torta Tre Monti (wafer cake) / Fagioli con cotiche (beans with pork rind)", phraseLanguage: "Italian", phraseHi: "Ciao", phraseMorning: "Buongiorno", phraseAfternoon: "Buon pomeriggio", funFact: "World's oldest republic — founded in 301 AD" },
  { name: "Serbia", flag: "🇷🇸", capital: "Belgrade", continent: "Europe", population: "~6.8M", currency: "Serbian Dinar", languages: "Serbian", nationalFood: "Ćevapi / Pljeskavica (Serbian smash burger) / Ajvar (roasted pepper spread)", phraseLanguage: "Serbian", phraseHi: "Zdravo", phraseMorning: "Dobro jutro", phraseAfternoon: "Dobar dan" },
  { name: "Slovakia", flag: "🇸🇰", capital: "Bratislava", continent: "Europe", population: "~5.5M", currency: "Euro", languages: "Slovak", nationalFood: "Bryndzové halušky (potato dumplings with sheep cheese and bacon)", phraseLanguage: "Slovak", phraseHi: "Ahoj / Dobrý deň", phraseMorning: "Dobré ráno", phraseAfternoon: "Dobré popoludnie" },
  { name: "Slovenia", flag: "🇸🇮", capital: "Ljubljana", continent: "Europe", population: "~2.1M", currency: "Euro", languages: "Slovenian", nationalFood: "Potica (walnut roll pastry) / Kranjska klobasa (Carniolan sausage)", phraseLanguage: "Slovenian", phraseHi: "Zdravo", phraseMorning: "Dobro jutro", phraseAfternoon: "Dober dan" },
  { name: "Spain", flag: "🇪🇸", capital: "Madrid", continent: "Europe", population: "~47M", currency: "Euro", languages: "Spanish (Castilian)", nationalFood: "Paella / Jamón ibérico / Tortilla española / Gazpacho", phraseLanguage: "Spanish", phraseHi: "Hola", phraseMorning: "Buenos días", phraseAfternoon: "Buenas tardes" },
  { name: "Sweden", flag: "🇸🇪", capital: "Stockholm", continent: "Europe", population: "~10.5M", currency: "Swedish Krona", languages: "Swedish", nationalFood: "Köttbullar (meatballs with gravy) / Gravlax / Surströmming", phraseLanguage: "Swedish", phraseHi: "Hej", phraseMorning: "God morgon", phraseAfternoon: "God eftermiddag" },
  { name: "Switzerland", flag: "🇨🇭", capital: "Bern", continent: "Europe", population: "~8.7M", currency: "Swiss Franc", languages: "German, French, Italian, Romansh", nationalFood: "Fondue / Raclette / Rösti / Swiss chocolate", phraseLanguage: "German", phraseHi: "Hallo / Grüezi", phraseMorning: "Guten Morgen", phraseAfternoon: "Guten Nachmittag", funFact: "Has not been at war since 1815 — one of the world's most neutral nations" },
  { name: "Ukraine", flag: "🇺🇦", capital: "Kyiv", continent: "Europe", population: "~43M", currency: "Ukrainian Hryvnia", languages: "Ukrainian", nationalFood: "Borscht / Varenyky (dumplings) / Chicken Kyiv", phraseLanguage: "Ukrainian", phraseHi: "Привіт (Pryvit)", phraseMorning: "Доброго ранку (Dobroho ranku)", phraseAfternoon: "Добрий день (Dobryi den)" },
  { name: "United Kingdom", flag: "🇬🇧", capital: "London", continent: "Europe", population: "~67M", currency: "Pound Sterling", languages: "English", nationalFood: "Fish and chips / Full English breakfast / Chicken tikka masala", phraseLanguage: "English", phraseHi: "Hi / Cheers", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon", funFact: "Once controlled the largest empire in history — covering a quarter of the Earth's land" },
  { name: "Vatican City", flag: "🇻🇦", capital: "Vatican City", continent: "Europe", population: "~0.0008M", currency: "Euro", languages: "Italian, Latin", nationalFood: "Supplì (fried rice balls) / Carciofi alla romana (Roman artichokes)", phraseLanguage: "Italian", phraseHi: "Ciao", phraseMorning: "Buongiorno", phraseAfternoon: "Buon pomeriggio", funFact: "Smallest country in the world by both area and population" },
];

const OCEANIA: C[] = [
  { name: "Australia", flag: "🇦🇺", capital: "Canberra", continent: "Oceania", population: "~26M", currency: "Australian Dollar", languages: "English", nationalFood: "Meat pie / Vegemite on toast / Lamington / Tim Tam", phraseLanguage: "English", phraseHi: "G'day", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon", funFact: "Only country that is also a continent" },
  { name: "Fiji", flag: "🇫🇯", capital: "Suva", continent: "Oceania", population: "~0.93M", currency: "Fijian Dollar", languages: "English, Fijian, Hindi", nationalFood: "Kokoda (raw fish marinated in lime and coconut milk)", phraseLanguage: "Fijian", phraseHi: "Bula!", phraseMorning: "Yadra (good morning)", phraseAfternoon: "Bula (general greeting)", funFact: "'Bula' means both hello and good health — a deeply meaningful word" },
  { name: "Kiribati", flag: "🇰🇮", capital: "South Tarawa", continent: "Oceania", population: "~0.12M", currency: "Australian Dollar", languages: "English, Gilbertese", nationalFood: "Te bua (fermented breadfruit) / Coconut crab", phraseLanguage: "Gilbertese", phraseHi: "Mauri", phraseMorning: "Mauri (general greeting)", phraseAfternoon: "Mauri", funFact: "First country to enter the new millennium — and first threatened by rising sea levels" },
  { name: "Marshall Islands", flag: "🇲🇭", capital: "Majuro", continent: "Oceania", population: "~0.04M", currency: "US Dollar", languages: "Marshallese, English", nationalFood: "Coconut-based dishes / Breadfruit / Tuna", phraseLanguage: "Marshallese", phraseHi: "Iōkwe (love to you)", phraseMorning: "Rainin in wōt (good morning)", phraseAfternoon: "Innām kōn tata (good afternoon)" },
  { name: "Micronesia", flag: "🇫🇲", capital: "Palikir", continent: "Oceania", population: "~0.11M", currency: "US Dollar", languages: "English, Chuukese, Pohnpeian", nationalFood: "Sakau (pepper drink) / Taro and breadfruit dishes", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Nauru", flag: "🇳🇷", capital: "Yaren (de facto)", continent: "Oceania", population: "~0.01M", currency: "Australian Dollar", languages: "Nauruan, English", nationalFood: "Flying fish / Coconut crab / Chinese-influenced dishes", phraseLanguage: "Nauruan", phraseHi: "Ekamawir", phraseMorning: "Ekamawir (greeting)", phraseAfternoon: "Ekamawir", funFact: "Third smallest country in the world — and once the world's richest per capita from phosphate mining" },
  { name: "New Zealand", flag: "🇳🇿", capital: "Wellington", continent: "Oceania", population: "~5M", currency: "New Zealand Dollar", languages: "English, Māori", nationalFood: "Hāngi (earth oven feast) / Pavlova / Lamb roast", phraseLanguage: "Māori", phraseHi: "Kia ora", phraseMorning: "Ata mārie (good morning)", phraseAfternoon: "Kia ora (general greeting)", funFact: "First country to give women the right to vote in 1893" },
  { name: "Palau", flag: "🇵🇼", capital: "Ngerulmud", continent: "Oceania", population: "~0.018M", currency: "US Dollar", languages: "Palauan, English", nationalFood: "Fruit bat soup / Taro / Seafood dishes", phraseLanguage: "Palauan", phraseHi: "Alii", phraseMorning: "Ungil tutau (good morning)", phraseAfternoon: "Ungil eongelel (good afternoon)" },
  { name: "Papua New Guinea", flag: "🇵🇬", capital: "Port Moresby", continent: "Oceania", population: "~10M", currency: "Papua New Guinean Kina", languages: "English, Tok Pisin, Hiri Motu", nationalFood: "Mumu (earth oven cooked pork and vegetables) / Sago", phraseLanguage: "Tok Pisin", phraseHi: "Gutpela apinun", phraseMorning: "Gutpela moning", phraseAfternoon: "Gutpela apinun", funFact: "Has the world's greatest linguistic diversity — over 800 languages spoken" },
  { name: "Samoa", flag: "🇼🇸", capital: "Apia", continent: "Oceania", population: "~0.22M", currency: "Samoan Tālā", languages: "Samoan, English", nationalFood: "Oka (raw fish in coconut cream) / Palusami (coconut cream in taro leaves)", phraseLanguage: "Samoan", phraseHi: "Talofa", phraseMorning: "Manuia le taeao", phraseAfternoon: "Manuia le aoauli" },
  { name: "Solomon Islands", flag: "🇸🇧", capital: "Honiara", continent: "Oceania", population: "~0.72M", currency: "Solomon Islands Dollar", languages: "English, Solomons Pijin", nationalFood: "Taro and sweet potato dishes / Coconut crab / Trochus", phraseLanguage: "English", phraseHi: "Hi", phraseMorning: "Good morning", phraseAfternoon: "Good afternoon" },
  { name: "Tonga", flag: "🇹🇴", capital: "Nukuʻalofa", continent: "Oceania", population: "~0.1M", currency: "Tongan Paʻanga", languages: "Tongan, English", nationalFood: "Lu pulu (corned beef and coconut cream baked in taro leaves)", phraseLanguage: "Tongan", phraseHi: "Mālō e lelei", phraseMorning: "Mālō e lelei (morning greeting)", phraseAfternoon: "Mālō e lelei" },
  { name: "Tuvalu", flag: "🇹🇻", capital: "Funafuti", continent: "Oceania", population: "~0.011M", currency: "Australian Dollar", languages: "Tuvaluan, English", nationalFood: "Pulaka (swamp taro) / Coconut dishes / Fish", phraseLanguage: "Tuvaluan", phraseHi: "Talofa", phraseMorning: "Talofa (greeting)", phraseAfternoon: "Talofa", funFact: "Could disappear entirely due to rising sea levels within decades" },
  { name: "Vanuatu", flag: "🇻🇺", capital: "Port Vila", continent: "Oceania", population: "~0.33M", currency: "Vanuatu Vatu", languages: "Bislama, English, French", nationalFood: "Lap lap (baked root vegetable and coconut milk — national dish)", phraseLanguage: "Bislama", phraseHi: "Halo", phraseMorning: "Gudmoning", phraseAfternoon: "Gudaftenun", funFact: "Consistently ranks among the happiest countries on the Happy Planet Index" },
];

async function main() {
  const continents = [AFRICA, AMERICAS, ASIA, MIDDLE_EAST, EUROPE, OCEANIA];

  // Interleave by continent so each day has variety
  const interleaved: C[] = [];
  let i = 0;
  let hasMore = true;
  while (hasMore) {
    hasMore = false;
    for (const group of continents) {
      if (i < group.length) { interleaved.push(group[i]); hasMore = true; }
    }
    i++;
  }

  const today = new Date();
  today.setHours(0, 0, 0, 0);

  let created = 0;
  let skipped = 0;

  for (let j = 0; j < interleaved.length; j++) {
    const dueAt = new Date(today);
    dueAt.setDate(dueAt.getDate() + j); // 1 per day

    const result = await prisma.country.upsert({
      where: { name: interleaved[j].name },
      update: {},
      create: { ...interleaved[j], dueAt },
    });

    if (result.createdAt.getTime() === result.dueAt.getTime() || j === 0) {
      created++;
    } else {
      skipped++;
    }
  }

  console.log(`✓ ${interleaved.length} countries processed (${created} created, ${skipped} skipped)`);
  console.log(`  Spanning ${interleaved.length} days — last intro: ${new Date(today.getTime() + (interleaved.length - 1) * 86400000).toDateString()}`);
}

main().catch(console.error).finally(() => prisma.$disconnect());
