import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.reviewLog.deleteMany();
  await prisma.card.deleteMany();
  await prisma.deck.deleteMany();
  await prisma.streak.deleteMany();

  const vocabularyDeck = await prisma.deck.create({
    data: {
      name: "Vocabulary",
      description: "Plain-English words and phrases you want to keep active.",
    },
  });

  const peopleDeck = await prisma.deck.create({
    data: {
      name: "People I care about",
      description: "A gentle place for names, family details, and current life context.",
    },
  });

  const founderDeck = await prisma.deck.create({
    data: {
      name: "Founder Vocabulary",
      description: "Language for explaining what you built in Japa Reality and Sharpen with clarity and confidence.",
    },
  });

  const today = new Date();

  await prisma.card.createMany({
    data: [
      {
        deckId: vocabularyDeck.id,
        front: "lucid",
        back: "Clear and easy to understand, especially when explaining something complex.",
        partOfSpeech: "adjective",
        example: "Her explanation of the API flow was lucid enough for a non-technical founder to follow.",
        hook: "Lucid sounds like light — the idea becomes bright and visible.",
        synonyms: "clear, intelligible",
        kind: "VOCABULARY",
        interval: 0,
        repetitions: 0,
        easeFactor: 2.5,
        dueAt: today,
      },
      {
        deckId: vocabularyDeck.id,
        front: "succinct",
        back: "Brief but meaningful; saying only what is needed without losing substance.",
        partOfSpeech: "adjective",
        example: "A succinct founder update is easier for investors to trust and remember.",
        hook: "Think of a sentence trimmed down to its strongest bones.",
        synonyms: "concise, compact",
        kind: "VOCABULARY",
        dueAt: today,
      },
      {
        deckId: vocabularyDeck.id,
        front: "nuance",
        back: "A subtle detail or distinction that changes how something should be understood.",
        partOfSpeech: "noun",
        example: "The nuance in the policy advice matters because migration routes differ by life situation.",
        hook: "Nuance is the small hinge that swings the big meaning.",
        synonyms: "subtlety, distinction",
        kind: "VOCABULARY",
        dueAt: today,
      },
      {
        deckId: vocabularyDeck.id,
        front: "cohesive",
        back: "Fitting together well so the whole feels connected and consistent.",
        partOfSpeech: "adjective",
        example: "The deck felt cohesive because every card reinforced the same product story.",
        hook: "Co-hesive: the pieces stick together.",
        synonyms: "unified, integrated",
        kind: "VOCABULARY",
        dueAt: today,
      },
      {
        deckId: vocabularyDeck.id,
        front: "articulate",
        back: "To express an idea clearly and effectively in speech or writing.",
        partOfSpeech: "verb",
        example: "He could articulate the trade-offs without sounding defensive.",
        hook: "Articulate means your thoughts have joints and move cleanly.",
        synonyms: "express, explain",
        kind: "VOCABULARY",
        dueAt: today,
      },
      {
        deckId: vocabularyDeck.id,
        front: "pragmatic",
        back: "Focused on what works in real life rather than what is ideal in theory.",
        partOfSpeech: "adjective",
        example: "A pragmatic rollout starts with one user and one clear ritual.",
        hook: "Pragmatic choices survive contact with reality.",
        synonyms: "practical, realistic",
        kind: "VOCABULARY",
        dueAt: today,
      },
      {
        deckId: vocabularyDeck.id,
        front: "retention",
        back: "The ability to keep information, customers, or users over time.",
        partOfSpeech: "noun",
        example: "Spaced repetition is really a retention system for memory.",
        hook: "Retention means something stays instead of slipping away.",
        synonyms: "preservation, continuity",
        kind: "VOCABULARY",
        dueAt: today,
      },
      {
        deckId: vocabularyDeck.id,
        front: "signal",
        back: "A meaningful sign that helps you interpret what is happening.",
        partOfSpeech: "noun",
        example: "User drop-off after payment is a strong signal worth investigating.",
        hook: "A signal cuts through noise.",
        synonyms: "indicator, cue",
        kind: "VOCABULARY",
        dueAt: today,
      },
      {
        deckId: vocabularyDeck.id,
        front: "friction",
        back: "Anything in a flow that makes progress slower, harder, or less likely.",
        partOfSpeech: "noun",
        example: "Too many form steps create friction before users reach value.",
        hook: "Like physical friction, it resists movement.",
        synonyms: "resistance, obstacle",
        kind: "VOCABULARY",
        dueAt: today,
      },
      {
        deckId: vocabularyDeck.id,
        front: "iterate",
        back: "To improve something through repeated cycles of testing and refinement.",
        partOfSpeech: "verb",
        example: "We iterate on the prompt until the output feels trustworthy.",
        hook: "Each loop tightens the work.",
        synonyms: "refine, revise",
        kind: "VOCABULARY",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "Migration readiness score",
        back: "A summary signal in Japa Reality that helps a user understand how prepared they are across practical dimensions like budget, timing, and profile fit.",
        partOfSpeech: "product concept",
        example: "The migration readiness score turns a complicated intake into one signal the user can act on.",
        hook: "It is a dashboard shorthand for preparedness, not a promise.",
        synonyms: "readiness signal, preparedness metric",
        kind: "FOUNDER",
        sourceContext: "Japa Reality uses profile-fit scoring across multiple dimensions to turn a messy migration decision into something easier to understand and discuss.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "Profile snapshot",
        back: "A saved user state in Japa Reality that preserves key migration details so the user can return without starting over.",
        partOfSpeech: "product concept",
        example: "The profile snapshot reduces form fatigue by letting users resume with their context intact.",
        hook: "Think of it as freezing the user’s current reality for later reuse.",
        synonyms: "saved state, profile memory",
        kind: "FOUNDER",
        sourceContext: "The Japa Reality backend includes profile snapshot and draft save endpoints to support continuity.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "Job Reality analysis",
        back: "A Japa Reality feature that analyses current job-market demand, salary signals, and sponsorship hints so a migration plan is grounded in actual market conditions.",
        partOfSpeech: "product concept",
        example: "Job Reality analysis keeps the migration advice from becoming abstract or overly optimistic.",
        hook: "It connects dream to market proof.",
        synonyms: "market analysis, demand snapshot",
        kind: "FOUNDER",
        sourceContext: "The app calls Adzuna and enriches paid-plan flows with job-market feedback and clickable links.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "Companion plan",
        back: "A subscription-style Japa Reality offer that extends beyond a one-off plan with updates, alerts, support, and ongoing execution help.",
        partOfSpeech: "offer design",
        example: "The Companion plan shifts the product from a single recommendation to an ongoing migration support relationship.",
        hook: "Companion implies walking beside the user, not just advising once.",
        synonyms: "ongoing support plan, continuity tier",
        kind: "FOUNDER",
        sourceContext: "The README and payment docs describe Companion as a monthly support layer with updates and dashboard access.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "Daily Depth Drill",
        back: "A Sharpen practice mode that serves one AI-generated question each day so users can repeatedly train depth, structure, and recall under realistic pressure.",
        partOfSpeech: "practice mode",
        example: "The Daily Depth Drill turns irregular study into a repeatable habit with visible feedback.",
        hook: "One deliberate rep a day compounds.",
        synonyms: "daily practice prompt, repetition ritual",
        kind: "FOUNDER",
        sourceContext: "Sharpen positions the drill as a cold-topic prompt that generates scorecards and flashcards from real gaps.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "Scorecard",
        back: "Sharpen’s structured feedback output that breaks an answer into dimensions like technical accuracy, clarity, depth, and conciseness.",
        partOfSpeech: "product artifact",
        example: "The scorecard makes weak spots concrete enough to improve, instead of leaving the user with a vague feeling.",
        hook: "A scorecard gives shape to performance.",
        synonyms: "feedback grid, evaluation breakdown",
        kind: "FOUNDER",
        sourceContext: "Sharpen repeatedly describes scorecards as the bridge between an answer and targeted flashcards or coaching.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "Gap-driven flashcards",
        back: "Flashcards generated from what the user specifically missed or explained weakly, rather than from a generic pre-made deck.",
        partOfSpeech: "learning mechanism",
        example: "Gap-driven flashcards make review feel relevant because every card points back to a real failure mode.",
        hook: "The card is born from a miss, so it returns with purpose.",
        synonyms: "personalised review cards, weakness-based flashcards",
        kind: "FOUNDER",
        sourceContext: "Sharpen’s landing copy repeatedly contrasts its flashcards with generic recall apps by tying them to real user answers.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "Teach-back selector",
        back: "A Sharpen mode where the user explains a concept as if teaching it, exposing whether understanding is merely familiar or truly internalised.",
        partOfSpeech: "practice mode",
        example: "Teach-back is useful because explanation under pressure reveals shallow understanding fast.",
        hook: "If you can teach it cleanly, you probably own it.",
        synonyms: "explanation drill, teaching mode",
        kind: "FOUNDER",
        sourceContext: "Sharpen includes teach-back as a dedicated practice route in the app structure.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "Articulation under pressure",
        back: "The skill of expressing what you know clearly when challenged in an interview, review, or live decision-making moment.",
        partOfSpeech: "founder language",
        example: "Both Sharpen and Soro Soke support articulation under pressure by making language easier to retrieve when it counts.",
        hook: "It is not just knowledge; it is knowledge that still works when the room goes quiet.",
        synonyms: "clear expression in the moment, performance clarity",
        kind: "FOUNDER",
        sourceContext: "Sharpen’s landing page emphasizes the gap between having depth and being able to express it when attention turns to you.",
        dueAt: today,
      },

      {
        deckId: founderDeck.id,
        front: "articulate",
        back: "To express an idea clearly, fluently, and with enough structure that other people understand both the point and its importance.",
        partOfSpeech: "verb",
        example: "I want to articulate the product value more clearly when I speak to investors or new users.",
        hook: "Articulate means your thinking moves with visible joints instead of coming out tangled.",
        synonyms: "express, explain clearly, communicate well",
        kind: "FOUNDER",
        sourceContext: "Useful when upgrading from general phrases like say, talk about, or explain.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "incorporate",
        back: "To bring an idea, feature, or insight into a product or explanation in a deliberate and integrated way.",
        partOfSpeech: "verb",
        example: "We incorporated founder-focused vocabulary into Soro Soke so the learning loop improves real communication.",
        hook: "Incorporate sounds like bringing something into the body of the work.",
        synonyms: "integrate, include, embed",
        kind: "FOUNDER",
        sourceContext: "A more polished alternative to just saying add.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "structure",
        back: "The way information is organised so it feels easy to follow, logically sequenced, and mentally clean.",
        partOfSpeech: "noun",
        example: "The card layout needs better structure so the definition and examples are easier to scan.",
        hook: "Structure is the skeleton that keeps ideas from collapsing into a pile.",
        synonyms: "organisation, framework, arrangement",
        kind: "FOUNDER",
        sourceContext: "Useful for product reviews, design feedback, and explaining ideas more professionally.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "polish",
        back: "To make something more refined, effective, and professional without changing its core meaning.",
        partOfSpeech: "verb",
        example: "I want to polish how I speak about the product so I sound more composed.",
        hook: "Polish keeps the object the same but improves the surface people first encounter.",
        synonyms: "refine, sharpen, improve",
        kind: "FOUNDER",
        sourceContext: "A strong founder word when improving speech, product copy, or demos.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "precise",
        back: "Exact and carefully chosen, with very little room for confusion or vagueness.",
        partOfSpeech: "adjective",
        example: "I need more precise language when I describe what the product actually does.",
        hook: "Precise language lands closer to the target with less wasted motion.",
        synonyms: "exact, accurate, specific",
        kind: "FOUNDER",
        sourceContext: "Useful when moving from broad intention to sharper communication.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "coherent",
        back: "Connected and logically consistent, so each part supports the whole explanation.",
        partOfSpeech: "adjective",
        example: "The pitch felt more coherent once the problem, product, and value were connected cleanly.",
        hook: "Coherent ideas hold together instead of pulling in different directions.",
        synonyms: "logical, unified, consistent",
        kind: "FOUNDER",
        sourceContext: "Helpful for evaluating talks, demos, product narratives, and written explanations.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "refine",
        back: "To improve something through adjustment, clarification, or sharpening rather than rebuilding it from scratch.",
        partOfSpeech: "verb",
        example: "I want to refine the way I describe the founder workflow so it sounds stronger.",
        hook: "Refine is improvement by sharpening, not by replacing everything.",
        synonyms: "improve, sharpen, clarify",
        kind: "FOUNDER",
        sourceContext: "A more strategic and professional word than fix in many founder contexts.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "succinct",
        back: "Brief but still meaningful, with no wasted words and no loss of substance.",
        partOfSpeech: "adjective",
        example: "I want my product explanation to be more succinct in networking conversations.",
        hook: "Succinct is short without becoming thin.",
        synonyms: "concise, compact, brief",
        kind: "FOUNDER",
        sourceContext: "Especially useful in intros, investor answers, and product demos.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "positioning",
        back: "How you frame a product so people immediately understand what it is, who it is for, and why it matters.",
        partOfSpeech: "noun",
        example: "Clear positioning helps people understand Soro Soke before I start talking about features.",
        hook: "Positioning is where your product sits in the listener’s mind.",
        synonyms: "framing, placement, market framing",
        kind: "FOUNDER",
        sourceContext: "A core founder communication term for product storytelling and market clarity.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "credible",
        back: "Believable and trustworthy because the explanation sounds grounded, clear, and supported by specifics.",
        partOfSpeech: "adjective",
        example: "Specific product language makes the pitch sound more credible.",
        hook: "Credible speech feels weight-bearing — it can carry trust.",
        synonyms: "trustworthy, convincing, believable",
        kind: "FOUNDER",
        sourceContext: "Useful when improving tone in investor conversations, networking, and product demos.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "review the build prompt and implement the app according to the specification",
        back: "A cleaner, more professional rewrite of a direct implementation request. It is more precise and sounds more deliberate.",
        partOfSpeech: "rewrite pattern",
        example: "Please review the build prompt and implement the app according to the specification.",
        hook: "Professional requests often become stronger by sounding intentional rather than rushed.",
        synonyms: "implementation request, scoped instruction",
        kind: "FOUNDER",
        sourceContext: "Rewrite upgrade from a shorter direct ask during the chat.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "help me strengthen the vocabulary I use as a startup founder",
        back: "A polished way to ask for language improvement support without sounding vague or awkward.",
        partOfSpeech: "rewrite pattern",
        example: "I’d also like the app to help me strengthen the vocabulary I use as a startup founder.",
        hook: "Strong phrasing often replaces clunky verb forms with smoother intention.",
        synonyms: "founder language improvement, vocabulary refinement",
        kind: "FOUNDER",
        sourceContext: "Rewrite upgrade from a request about building vocabulary as a founder.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "incorporate that context into Soro Soke",
        back: "A more product-minded and professional alternative to saying add it to Soro Soke.",
        partOfSpeech: "rewrite pattern",
        example: "Please review both projects and incorporate that context into Soro Soke.",
        hook: "Incorporate suggests thoughtful integration, not just attachment.",
        synonyms: "integrate into the product, apply product context",
        kind: "FOUNDER",
        sourceContext: "Rewrite upgrade from a request to review sibling apps and use them inside Soro Soke.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "the layout needs better structure",
        back: "A stronger and more design-literate way to describe UI formatting issues.",
        partOfSpeech: "rewrite pattern",
        example: "The vocabulary card layout needs better structure — the definition and related fields are not visually well organized.",
        hook: "Good product feedback identifies the design problem, not just the frustration.",
        synonyms: "layout feedback, UI clarity diagnosis",
        kind: "FOUNDER",
        sourceContext: "Rewrite upgrade from feedback about card formatting.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "produce smarter, more dynamic suggestions",
        back: "A more polished way to describe AI output quality goals in a product feature.",
        partOfSpeech: "rewrite pattern",
        example: "How do I add the AI API key so the card generator can produce smarter, more dynamic suggestions?",
        hook: "Specific capability language makes technical requests easier to act on.",
        synonyms: "AI output quality, stronger generation behavior",
        kind: "FOUNDER",
        sourceContext: "Rewrite upgrade from a request about making the generator dynamic and smart.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "the full project has not been pushed yet",
        back: "A clearer and more professional way to describe incomplete GitHub publication.",
        partOfSpeech: "rewrite pattern",
        example: "The GitHub repository exists, but it looks like the full project has not been pushed yet.",
        hook: "Good technical phrasing names the exact problem state instead of sounding half-formed.",
        synonyms: "repo state clarification, deployment status wording",
        kind: "FOUNDER",
        sourceContext: "Rewrite upgrade from uncertainty about GitHub state.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "where should it appear in the app",
        back: "A better way to ask about a missing feature in a collaborative product-building conversation.",
        partOfSpeech: "rewrite pattern",
        example: "I don’t see the founder vocabulary batch generation feature yet. Where should it appear in the app?",
        hook: "Strong debugging questions combine observation with a precise follow-up.",
        synonyms: "feature discovery question, UI placement clarification",
        kind: "FOUNDER",
        sourceContext: "Rewrite upgrade from asking where the founder generation feature was.",
        dueAt: today,
      },
      {
        deckId: founderDeck.id,
        front: "identify stronger words or phrases I could have used",
        back: "A reflective and polished way to request communication coaching based on real conversation.",
        partOfSpeech: "rewrite pattern",
        example: "Please review how I expressed myself today and identify stronger words or phrases I could have used to sound clearer and more polished.",
        hook: "Founder communication improves faster when the request for feedback is itself clear and structured.",
        synonyms: "communication coaching request, articulation refinement prompt",
        kind: "FOUNDER",
        sourceContext: "Rewrite upgrade from a request to review today’s articulation and suggest stronger language.",
        dueAt: today,
      },

      {
        deckId: founderDeck.id,
        front: "Founder articulation deck",
        back: "A Soro Soke deck dedicated to helping you explain your own products, decisions, and mechanisms with more precise language and recall.",
        partOfSpeech: "meta concept",
        example: "The founder articulation deck gives product language its own review loop so explanation becomes easier over time.",
        hook: "You are not only remembering facts; you are rehearsing clarity.",
        synonyms: "founder vocabulary set, product explanation deck",
        kind: "FOUNDER",
        sourceContext: "This deck is intentionally seeded from Japa Reality and Sharpen so Soro Soke supports how you speak about what you have built.",
        dueAt: today,
      },
    ],
  });

  await prisma.streak.create({ data: { currentStreak: 0, lastReviewDate: null } });

  console.log(`Seeded decks: ${vocabularyDeck.name}, ${peopleDeck.name}, ${founderDeck.name}`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
